travis_fold:start:worker_info[0K[33;1mWorker information[0m
hostname: i-02d32f8-precise-production-2-worker-org-docker.travisci.net:93110881-c438-42ea-a977-5e24d25a9984
version: v2.5.0 https://github.com/travis-ci/worker/tree/da3a43228dffc0fcca5a46569ca786b22991979f
instance: 2616b17:travis:python
startup: 1.005899335s
travis_fold:end:worker_info[0Ktravis_fold:start:system_info[0K[33;1mBuild system information[0m
Build language: python
Build group: stable
Build dist: precise
Build id: 221711307
Job id: 221711308
travis-build version: 4a669c7bf
[34m[1mBuild image provisioning date and time[0m
Thu Feb  5 15:09:33 UTC 2015
[34m[1mOperating System Details[0m
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise
[34m[1mLinux Version[0m
3.13.0-29-generic
[34m[1mCookbooks Version[0m
a68419e https://github.com/travis-ci/travis-cookbooks/tree/a68419e
[34m[1mGCC version[0m
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[34m[1mLLVM version[0m
clang version 3.4 (tags/RELEASE_34/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
[34m[1mPre-installed Ruby versions[0m
ruby-1.9.3-p551
[34m[1mPre-installed Node.js versions[0m
v0.10.36
[34m[1mPre-installed Go versions[0m
1.4.1
[34m[1mRedis version[0m
redis-server 2.8.19
[34m[1mriak version[0m
2.0.2
[34m[1mMongoDB version[0m
MongoDB 2.4.12
[34m[1mCouchDB version[0m
couchdb 1.6.1
[34m[1mNeo4j version[0m
1.9.4
[34m[1mRabbitMQ Version[0m
3.4.3
[34m[1mElasticSearch version[0m
1.4.0
[34m[1mInstalled Sphinx versions[0m
2.0.10
2.1.9
2.2.6
[34m[1mDefault Sphinx version[0m
2.2.6
[34m[1mInstalled Firefox version[0m
firefox 31.0esr
[34m[1mPhantomJS version[0m
1.9.8
[34m[1mant -version[0m
Apache Ant(TM) version 1.8.2 compiled on December 3 2011
[34m[1mmvn -version[0m
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T17:29:23+00:00)
Maven home: /usr/local/maven
Java version: 1.7.0_76, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-oracle/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "3.13.0-29-generic", arch: "amd64", family: "unix"
travis_fold:end:system_info[0K
travis_fold:start:fix.CVE-2015-7547[0K$ export DEBIAN_FRONTEND=noninteractive
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  libc-bin libc-dev-bin libc6-dev
Suggested packages:
  glibc-doc
The following packages will be upgraded:
  libc-bin libc-dev-bin libc6 libc6-dev
4 upgraded, 0 newly installed, 0 to remove and 262 not upgraded.
Need to get 8,856 kB of archives.
After this operation, 13.3 kB of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu/ precise-updates/main libc6-dev amd64 2.15-0ubuntu10.18 [2,948 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu/ precise-updates/main libc-dev-bin amd64 2.15-0ubuntu10.18 [84.5 kB]
Get:3 http://us.archive.ubuntu.com/ubuntu/ precise-updates/main libc-bin amd64 2.15-0ubuntu10.18 [1,178 kB]
Get:4 http://us.archive.ubuntu.com/ubuntu/ precise-updates/main libc6 amd64 2.15-0ubuntu10.18 [4,646 kB]
Fetched 8,856 kB in 0s (34.9 MB/s)
Preconfiguring packages ...
(Reading database ... (Reading database ... 5%(Reading database ... 10%(Reading database ... 15%(Reading database ... 20%(Reading database ... 25%(Reading database ... 30%(Reading database ... 35%(Reading database ... 40%(Reading database ... 45%(Reading database ... 50%(Reading database ... 55%(Reading database ... 60%(Reading database ... 65%(Reading database ... 70%(Reading database ... 75%(Reading database ... 80%(Reading database ... 85%(Reading database ... 90%(Reading database ... 95%(Reading database ... 100%(Reading database ... 72431 files and directories currently installed.)
Preparing to replace libc6-dev 2.15-0ubuntu10.10 (using .../libc6-dev_2.15-0ubuntu10.18_amd64.deb) ...
Unpacking replacement libc6-dev ...
Preparing to replace libc-dev-bin 2.15-0ubuntu10.10 (using .../libc-dev-bin_2.15-0ubuntu10.18_amd64.deb) ...
Unpacking replacement libc-dev-bin ...
Preparing to replace libc-bin 2.15-0ubuntu10.10 (using .../libc-bin_2.15-0ubuntu10.18_amd64.deb) ...
Unpacking replacement libc-bin ...
Processing triggers for man-db ...
Setting up libc-bin (2.15-0ubuntu10.18) ...
(Reading database ... (Reading database ... 5%(Reading database ... 10%(Reading database ... 15%(Reading database ... 20%(Reading database ... 25%(Reading database ... 30%(Reading database ... 35%(Reading database ... 40%(Reading database ... 45%(Reading database ... 50%(Reading database ... 55%(Reading database ... 60%(Reading database ... 65%(Reading database ... 70%(Reading database ... 75%(Reading database ... 80%(Reading database ... 85%(Reading database ... 90%(Reading database ... 95%(Reading database ... 100%(Reading database ... 72430 files and directories currently installed.)
Preparing to replace libc6 2.15-0ubuntu10.10 (using .../libc6_2.15-0ubuntu10.18_amd64.deb) ...
Unpacking replacement libc6 ...
Setting up libc6 (2.15-0ubuntu10.18) ...
Setting up libc-dev-bin (2.15-0ubuntu10.18) ...
Setting up libc6-dev (2.15-0ubuntu10.18) ...
Processing triggers for libc-bin ...
ldconfig deferred processing now taking place
travis_fold:end:fix.CVE-2015-7547[0K[33;1m3.5 is not installed; attempting download[0m
[33;1mDownloading archive: https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/12.04/x86_64/python-3.5.tar.bz2[0m
$ sudo tar xjf python-3.5.tar.bz2 --directory /
travis_fold:start:git.checkout[0Ktravis_time:start:1d7817d1[0K$ git clone --depth=50 --branch=master https://github.com/GNS3/gns3-server.git GNS3/gns3-server
Cloning into 'GNS3/gns3-server'...
remote: Counting objects: 757, done.[K
remote: Compressing objects:   0% (1/492)   [Kremote: Compressing objects:   1% (5/492)   [Kremote: Compressing objects:   2% (10/492)   [Kremote: Compressing objects:   3% (15/492)   [Kremote: Compressing objects:   4% (20/492)   [Kremote: Compressing objects:   5% (25/492)   [Kremote: Compressing objects:   6% (30/492)   [Kremote: Compressing objects:   7% (35/492)   [Kremote: Compressing objects:   8% (40/492)   [Kremote: Compressing objects:   9% (45/492)   [Kremote: Compressing objects:  10% (50/492)   [Kremote: Compressing objects:  11% (55/492)   [Kremote: Compressing objects:  12% (60/492)   [Kremote: Compressing objects:  13% (64/492)   [Kremote: Compressing objects:  14% (69/492)   [Kremote: Compressing objects:  15% (74/492)   [Kremote: Compressing objects:  16% (79/492)   [Kremote: Compressing objects:  17% (84/492)   [Kremote: Compressing objects:  18% (89/492)   [Kremote: Compressing objects:  19% (94/492)   [Kremote: Compressing objects:  20% (99/492)   [Kremote: Compressing objects:  21% (104/492)   [Kremote: Compressing objects:  22% (109/492)   [Kremote: Compressing objects:  23% (114/492)   [Kremote: Compressing objects:  24% (119/492)   [Kremote: Compressing objects:  25% (123/492)   [Kremote: Compressing objects:  26% (128/492)   [Kremote: Compressing objects:  27% (133/492)   [Kremote: Compressing objects:  28% (138/492)   [Kremote: Compressing objects:  29% (143/492)   [Kremote: Compressing objects:  30% (148/492)   [Kremote: Compressing objects:  31% (153/492)   [Kremote: Compressing objects:  32% (158/492)   [Kremote: Compressing objects:  33% (163/492)   [Kremote: Compressing objects:  34% (168/492)   [Kremote: Compressing objects:  35% (173/492)   [Kremote: Compressing objects:  36% (178/492)   [Kremote: Compressing objects:  37% (183/492)   [Kremote: Compressing objects:  38% (187/492)   [Kremote: Compressing objects:  39% (192/492)   [Kremote: Compressing objects:  40% (197/492)   [Kremote: Compressing objects:  41% (202/492)   [Kremote: Compressing objects:  42% (207/492)   [Kremote: Compressing objects:  43% (212/492)   [Kremote: Compressing objects:  44% (217/492)   [Kremote: Compressing objects:  45% (222/492)   [Kremote: Compressing objects:  46% (227/492)   [Kremote: Compressing objects:  47% (232/492)   [Kremote: Compressing objects:  48% (237/492)   [Kremote: Compressing objects:  49% (242/492)   [Kremote: Compressing objects:  50% (246/492)   [Kremote: Compressing objects:  51% (251/492)   [Kremote: Compressing objects:  52% (256/492)   [Kremote: Compressing objects:  53% (261/492)   [Kremote: Compressing objects:  54% (266/492)   [Kremote: Compressing objects:  55% (271/492)   [Kremote: Compressing objects:  56% (276/492)   [Kremote: Compressing objects:  57% (281/492)   [Kremote: Compressing objects:  58% (286/492)   [Kremote: Compressing objects:  59% (291/492)   [Kremote: Compressing objects:  60% (296/492)   [Kremote: Compressing objects:  61% (301/492)   [Kremote: Compressing objects:  62% (306/492)   [Kremote: Compressing objects:  63% (310/492)   [Kremote: Compressing objects:  64% (315/492)   [Kremote: Compressing objects:  65% (320/492)   [Kremote: Compressing objects:  66% (325/492)   [Kremote: Compressing objects:  67% (330/492)   [Kremote: Compressing objects:  68% (335/492)   [Kremote: Compressing objects:  69% (340/492)   [Kremote: Compressing objects:  70% (345/492)   [Kremote: Compressing objects:  71% (350/492)   [Kremote: Compressing objects:  72% (355/492)   [Kremote: Compressing objects:  73% (360/492)   [Kremote: Compressing objects:  74% (365/492)   [Kremote: Compressing objects:  75% (369/492)   [Kremote: Compressing objects:  76% (374/492)   [Kremote: Compressing objects:  77% (379/492)   [Kremote: Compressing objects:  78% (384/492)   [Kremote: Compressing objects:  79% (389/492)   [Kremote: Compressing objects:  80% (394/492)   [Kremote: Compressing objects:  81% (399/492)   [Kremote: Compressing objects:  82% (404/492)   [Kremote: Compressing objects:  83% (409/492)   [Kremote: Compressing objects:  84% (414/492)   [Kremote: Compressing objects:  85% (419/492)   [Kremote: Compressing objects:  86% (424/492)   [Kremote: Compressing objects:  87% (429/492)   [Kremote: Compressing objects:  88% (433/492)   [Kremote: Compressing objects:  89% (438/492)   [Kremote: Compressing objects:  90% (443/492)   [Kremote: Compressing objects:  91% (448/492)   [Kremote: Compressing objects:  92% (453/492)   [Kremote: Compressing objects:  93% (458/492)   [Kremote: Compressing objects:  94% (463/492)   [Kremote: Compressing objects:  95% (468/492)   [Kremote: Compressing objects:  96% (473/492)   [Kremote: Compressing objects:  97% (478/492)   [Kremote: Compressing objects:  98% (483/492)   [Kremote: Compressing objects:  99% (488/492)   [Kremote: Compressing objects: 100% (492/492)   [Kremote: Compressing objects: 100% (492/492), done.[K
Receiving objects:   0% (1/757)   Receiving objects:   1% (8/757)   Receiving objects:   2% (16/757)   Receiving objects:   3% (23/757)   Receiving objects:   4% (31/757)   Receiving objects:   5% (38/757)   Receiving objects:   6% (46/757)   Receiving objects:   7% (53/757)   Receiving objects:   8% (61/757)   Receiving objects:   9% (69/757)   Receiving objects:  10% (76/757)   Receiving objects:  11% (84/757)   Receiving objects:  12% (91/757)   Receiving objects:  13% (99/757)   Receiving objects:  14% (106/757)   Receiving objects:  15% (114/757)   Receiving objects:  16% (122/757)   Receiving objects:  17% (129/757)   Receiving objects:  18% (137/757)   Receiving objects:  19% (144/757)   Receiving objects:  20% (152/757)   Receiving objects:  21% (159/757)   Receiving objects:  22% (167/757)   Receiving objects:  23% (175/757)   Receiving objects:  24% (182/757)   Receiving objects:  25% (190/757)   Receiving objects:  26% (197/757)   Receiving objects:  27% (205/757)   Receiving objects:  28% (212/757)   Receiving objects:  29% (220/757)   Receiving objects:  30% (228/757)   Receiving objects:  31% (235/757)   Receiving objects:  32% (243/757)   Receiving objects:  33% (250/757)   Receiving objects:  34% (258/757)   Receiving objects:  35% (265/757)   Receiving objects:  36% (273/757)   Receiving objects:  37% (281/757)   Receiving objects:  38% (288/757)   Receiving objects:  39% (296/757)   Receiving objects:  40% (303/757)   Receiving objects:  41% (311/757)   Receiving objects:  42% (318/757)   Receiving objects:  43% (326/757)   Receiving objects:  44% (334/757)   Receiving objects:  45% (341/757)   Receiving objects:  46% (349/757)   Receiving objects:  47% (356/757)   Receiving objects:  48% (364/757)   Receiving objects:  49% (371/757)   Receiving objects:  50% (379/757)   Receiving objects:  51% (387/757)   Receiving objects:  52% (394/757)   Receiving objects:  53% (402/757)   Receiving objects:  54% (409/757)   Receiving objects:  55% (417/757)   Receiving objects:  56% (424/757)   Receiving objects:  57% (432/757)   Receiving objects:  58% (440/757)   Receiving objects:  59% (447/757)   Receiving objects:  60% (455/757)   Receiving objects:  61% (462/757)   Receiving objects:  62% (470/757)   Receiving objects:  63% (477/757)   Receiving objects:  64% (485/757)   Receiving objects:  65% (493/757)   Receiving objects:  66% (500/757)   Receiving objects:  67% (508/757)   Receiving objects:  68% (515/757)   Receiving objects:  69% (523/757)   Receiving objects:  70% (530/757)   Receiving objects:  71% (538/757)   Receiving objects:  72% (546/757)   Receiving objects:  73% (553/757)   Receiving objects:  74% (561/757)   Receiving objects:  75% (568/757)   Receiving objects:  76% (576/757)   Receiving objects:  77% (583/757)   Receiving objects:  78% (591/757)   Receiving objects:  79% (599/757)   Receiving objects:  80% (606/757)   Receiving objects:  81% (614/757)   Receiving objects:  82% (621/757)   Receiving objects:  83% (629/757)   Receiving objects:  84% (636/757)   Receiving objects:  85% (644/757)   Receiving objects:  86% (652/757)   Receiving objects:  87% (659/757)   Receiving objects:  88% (667/757)   Receiving objects:  89% (674/757)   Receiving objects:  90% (682/757)   Receiving objects:  91% (689/757)   Receiving objects:  92% (697/757)   Receiving objects:  93% (705/757)   Receiving objects:  94% (712/757)   Receiving objects:  95% (720/757)   remote: Total 757 (delta 452), reused 389 (delta 245), pack-reused 0[K
Receiving objects:  96% (727/757)   Receiving objects:  97% (735/757)   Receiving objects:  98% (742/757)   Receiving objects:  99% (750/757)   Receiving objects: 100% (757/757)   Receiving objects: 100% (757/757), 975.65 KiB | 0 bytes/s, done.
Resolving deltas:   0% (0/452)   Resolving deltas:   1% (6/452)   Resolving deltas:   3% (14/452)   Resolving deltas:   5% (26/452)   Resolving deltas:   7% (32/452)   Resolving deltas:  18% (83/452)   Resolving deltas:  19% (90/452)   Resolving deltas:  20% (94/452)   Resolving deltas:  21% (96/452)   Resolving deltas:  22% (101/452)   Resolving deltas:  23% (104/452)   Resolving deltas:  25% (115/452)   Resolving deltas:  26% (119/452)   Resolving deltas:  27% (123/452)   Resolving deltas:  28% (129/452)   Resolving deltas:  30% (139/452)   Resolving deltas:  32% (148/452)   Resolving deltas:  33% (150/452)   Resolving deltas:  35% (159/452)   Resolving deltas:  37% (168/452)   Resolving deltas:  38% (176/452)   Resolving deltas:  39% (177/452)   Resolving deltas:  40% (184/452)   Resolving deltas:  42% (190/452)   Resolving deltas:  45% (206/452)   Resolving deltas:  47% (214/452)   Resolving deltas:  50% (227/452)   Resolving deltas:  51% (234/452)   Resolving deltas:  52% (238/452)   Resolving deltas:  53% (241/452)   Resolving deltas:  54% (245/452)   Resolving deltas:  56% (256/452)   Resolving deltas:  57% (259/452)   Resolving deltas:  61% (279/452)   Resolving deltas:  62% (283/452)   Resolving deltas:  63% (285/452)   Resolving deltas:  67% (305/452)   Resolving deltas:  68% (309/452)   Resolving deltas:  69% (316/452)   Resolving deltas:  71% (323/452)   Resolving deltas:  72% (327/452)   Resolving deltas:  73% (333/452)   Resolving deltas:  78% (357/452)   Resolving deltas:  82% (373/452)   Resolving deltas:  83% (377/452)   Resolving deltas:  84% (380/452)   Resolving deltas:  85% (388/452)   Resolving deltas:  86% (389/452)   Resolving deltas:  88% (398/452)   Resolving deltas:  89% (405/452)   Resolving deltas:  90% (407/452)   Resolving deltas:  91% (412/452)   Resolving deltas:  92% (416/452)   Resolving deltas:  93% (424/452)   Resolving deltas:  94% (427/452)   Resolving deltas:  95% (430/452)   Resolving deltas:  96% (434/452)   Resolving deltas:  97% (439/452)   Resolving deltas:  98% (443/452)   Resolving deltas:  99% (448/452)   Resolving deltas: 100% (452/452)   Resolving deltas: 100% (452/452), done.
Checking connectivity... done.

travis_time:end:1d7817d1:start=1492086398403765779,finish=1492086399026157820,duration=622392041[0K$ cd GNS3/gns3-server
$ git checkout -qf 3afe85ba3c9e142d5b1e0aef3bfe879d216c593c
travis_fold:end:git.checkout[0Ktravis_time:start:225f63ae[0K$ source ~/virtualenv/python3.5/bin/activate

travis_time:end:225f63ae:start=1492086405454619130,finish=1492086405459097973,duration=4478843[0Ktravis_fold:start:cache.1[0KSetting up build cache
$ export CASHER_DIR=$HOME/.casher
travis_time:start:2dd1ccfc[0K$ Installing caching utilities

travis_time:end:2dd1ccfc:start=1492086405678743927,finish=1492086405719108513,duration=40364586[0Ktravis_time:start:19ec3368[0K
travis_time:end:19ec3368:start=1492086405725122639,finish=1492086405729390199,duration=4267560[0Ktravis_time:start:16916700[0K[32;1mattempting to download cache archive[0m
[32;1mfetching master/cache-linux-precise-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855--python-3.5.tgz[0m
[32;1mfound cache[0m

travis_time:end:16916700:start=1492086405734108829,finish=1492086406497029457,duration=762920628[0Ktravis_fold:end:cache.1[0Ktravis_fold:start:cache.pip[0K
travis_time:start:124078d0[0K
travis_time:end:124078d0:start=1492086406503070799,finish=1492086406507762124,duration=4691325[0Ktravis_time:start:0494e590[0K[32;1madding /home/travis/.cache/pip to cache[0m

travis_time:end:0494e590:start=1492086406518735138,finish=1492086408470406700,duration=1951671562[0Ktravis_fold:end:cache.pip[0K$ python --version
Python 3.5.2
$ pip --version
pip 9.0.1 from /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages (python 3.5)
travis_fold:start:install.1[0Ktravis_time:start:0400f684[0K$ python setup.py install
/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/setuptools/dist.py:333: UserWarning: Normalizing '1.5.4dev1' to '1.5.4.dev1'
  normalized_version,
running install
running bdist_egg
running egg_info
creating gns3_server.egg-info
writing entry points to gns3_server.egg-info/entry_points.txt
writing requirements to gns3_server.egg-info/requires.txt
writing dependency_links to gns3_server.egg-info/dependency_links.txt
writing gns3_server.egg-info/PKG-INFO
writing top-level names to gns3_server.egg-info/top_level.txt
writing manifest file 'gns3_server.egg-info/SOURCES.txt'
reading manifest file 'gns3_server.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'INSTALL'
warning: no previously-included files matching '*' found under directory 'docs'
warning: no previously-included files matching '__pycache__' found under directory '*'
writing manifest file 'gns3_server.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/gns3server
copying gns3server/__init__.py -> build/lib/gns3server
copying gns3server/__main__.py -> build/lib/gns3server
copying gns3server/config.py -> build/lib/gns3server
copying gns3server/crash_report.py -> build/lib/gns3server
copying gns3server/main.py -> build/lib/gns3server
copying gns3server/run.py -> build/lib/gns3server
copying gns3server/server.py -> build/lib/gns3server
copying gns3server/version.py -> build/lib/gns3server
creating build/lib/gns3server/controller
copying gns3server/controller/__init__.py -> build/lib/gns3server/controller
creating build/lib/gns3server/handlers
copying gns3server/handlers/__init__.py -> build/lib/gns3server/handlers
copying gns3server/handlers/index_handler.py -> build/lib/gns3server/handlers
copying gns3server/handlers/upload_handler.py -> build/lib/gns3server/handlers
creating build/lib/gns3server/modules
copying gns3server/modules/__init__.py -> build/lib/gns3server/modules
copying gns3server/modules/base_manager.py -> build/lib/gns3server/modules
copying gns3server/modules/base_vm.py -> build/lib/gns3server/modules
copying gns3server/modules/port_manager.py -> build/lib/gns3server/modules
copying gns3server/modules/project.py -> build/lib/gns3server/modules
copying gns3server/modules/project_manager.py -> build/lib/gns3server/modules
copying gns3server/modules/vm_error.py -> build/lib/gns3server/modules
creating build/lib/gns3server/schemas
copying gns3server/schemas/__init__.py -> build/lib/gns3server/schemas
copying gns3server/schemas/docker.py -> build/lib/gns3server/schemas
copying gns3server/schemas/dynamips_device.py -> build/lib/gns3server/schemas
copying gns3server/schemas/dynamips_vm.py -> build/lib/gns3server/schemas
copying gns3server/schemas/file.py -> build/lib/gns3server/schemas
copying gns3server/schemas/iou.py -> build/lib/gns3server/schemas
copying gns3server/schemas/nio.py -> build/lib/gns3server/schemas
copying gns3server/schemas/project.py -> build/lib/gns3server/schemas
copying gns3server/schemas/qemu.py -> build/lib/gns3server/schemas
copying gns3server/schemas/version.py -> build/lib/gns3server/schemas
copying gns3server/schemas/virtualbox.py -> build/lib/gns3server/schemas
copying gns3server/schemas/vm.py -> build/lib/gns3server/schemas
copying gns3server/schemas/vmware.py -> build/lib/gns3server/schemas
copying gns3server/schemas/vpcs.py -> build/lib/gns3server/schemas
creating build/lib/gns3server/ubridge
copying gns3server/ubridge/__init__.py -> build/lib/gns3server/ubridge
copying gns3server/ubridge/hypervisor.py -> build/lib/gns3server/ubridge
copying gns3server/ubridge/ubridge_error.py -> build/lib/gns3server/ubridge
copying gns3server/ubridge/ubridge_hypervisor.py -> build/lib/gns3server/ubridge
creating build/lib/gns3server/utils
copying gns3server/utils/__init__.py -> build/lib/gns3server/utils
copying gns3server/utils/get_resource.py -> build/lib/gns3server/utils
copying gns3server/utils/images.py -> build/lib/gns3server/utils
copying gns3server/utils/interfaces.py -> build/lib/gns3server/utils
copying gns3server/utils/telnet_server.py -> build/lib/gns3server/utils
copying gns3server/utils/vmnet.py -> build/lib/gns3server/utils
creating build/lib/gns3server/web
copying gns3server/web/__init__.py -> build/lib/gns3server/web
copying gns3server/web/documentation.py -> build/lib/gns3server/web
copying gns3server/web/logger.py -> build/lib/gns3server/web
copying gns3server/web/response.py -> build/lib/gns3server/web
copying gns3server/web/route.py -> build/lib/gns3server/web
creating build/lib/gns3server/handlers/api
copying gns3server/handlers/api/__init__.py -> build/lib/gns3server/handlers/api
copying gns3server/handlers/api/config_handler.py -> build/lib/gns3server/handlers/api
copying gns3server/handlers/api/docker_handler.py -> build/lib/gns3server/handlers/api
copying gns3server/handlers/api/dynamips_device_handler.py -> build/lib/gns3server/handlers/api
copying gns3server/handlers/api/dynamips_vm_handler.py -> build/lib/gns3server/handlers/api
copying gns3server/handlers/api/file_handler.py -> build/lib/gns3server/handlers/api
copying gns3server/handlers/api/iou_handler.py -> build/lib/gns3server/handlers/api
copying gns3server/handlers/api/network_handler.py -> build/lib/gns3server/handlers/api
copying gns3server/handlers/api/project_handler.py -> build/lib/gns3server/handlers/api
copying gns3server/handlers/api/qemu_handler.py -> build/lib/gns3server/handlers/api
copying gns3server/handlers/api/server_handler.py -> build/lib/gns3server/handlers/api
copying gns3server/handlers/api/version_handler.py -> build/lib/gns3server/handlers/api
copying gns3server/handlers/api/virtualbox_handler.py -> build/lib/gns3server/handlers/api
copying gns3server/handlers/api/vmware_handler.py -> build/lib/gns3server/handlers/api
copying gns3server/handlers/api/vpcs_handler.py -> build/lib/gns3server/handlers/api
creating build/lib/gns3server/modules/adapters
copying gns3server/modules/adapters/__init__.py -> build/lib/gns3server/modules/adapters
copying gns3server/modules/adapters/adapter.py -> build/lib/gns3server/modules/adapters
copying gns3server/modules/adapters/ethernet_adapter.py -> build/lib/gns3server/modules/adapters
copying gns3server/modules/adapters/serial_adapter.py -> build/lib/gns3server/modules/adapters
creating build/lib/gns3server/modules/docker
copying gns3server/modules/docker/__init__.py -> build/lib/gns3server/modules/docker
copying gns3server/modules/docker/docker_error.py -> build/lib/gns3server/modules/docker
copying gns3server/modules/docker/docker_vm.py -> build/lib/gns3server/modules/docker
creating build/lib/gns3server/modules/dynamips
copying gns3server/modules/dynamips/__init__.py -> build/lib/gns3server/modules/dynamips
copying gns3server/modules/dynamips/dynamips_device.py -> build/lib/gns3server/modules/dynamips
copying gns3server/modules/dynamips/dynamips_error.py -> build/lib/gns3server/modules/dynamips
copying gns3server/modules/dynamips/dynamips_hypervisor.py -> build/lib/gns3server/modules/dynamips
copying gns3server/modules/dynamips/dynamips_vm.py -> build/lib/gns3server/modules/dynamips
copying gns3server/modules/dynamips/hypervisor.py -> build/lib/gns3server/modules/dynamips
creating build/lib/gns3server/modules/iou
copying gns3server/modules/iou/__init__.py -> build/lib/gns3server/modules/iou
copying gns3server/modules/iou/iou_error.py -> build/lib/gns3server/modules/iou
copying gns3server/modules/iou/iou_vm.py -> build/lib/gns3server/modules/iou
copying gns3server/modules/iou/ioucon.py -> build/lib/gns3server/modules/iou
creating build/lib/gns3server/modules/nios
copying gns3server/modules/nios/__init__.py -> build/lib/gns3server/modules/nios
copying gns3server/modules/nios/nio.py -> build/lib/gns3server/modules/nios
copying gns3server/modules/nios/nio_generic_ethernet.py -> build/lib/gns3server/modules/nios
copying gns3server/modules/nios/nio_nat.py -> build/lib/gns3server/modules/nios
copying gns3server/modules/nios/nio_tap.py -> build/lib/gns3server/modules/nios
copying gns3server/modules/nios/nio_udp.py -> build/lib/gns3server/modules/nios
creating build/lib/gns3server/modules/qemu
copying gns3server/modules/qemu/__init__.py -> build/lib/gns3server/modules/qemu
copying gns3server/modules/qemu/qcow2.py -> build/lib/gns3server/modules/qemu
copying gns3server/modules/qemu/qemu_error.py -> build/lib/gns3server/modules/qemu
copying gns3server/modules/qemu/qemu_vm.py -> build/lib/gns3server/modules/qemu
creating build/lib/gns3server/modules/virtualbox
copying gns3server/modules/virtualbox/__init__.py -> build/lib/gns3server/modules/virtualbox
copying gns3server/modules/virtualbox/virtualbox_error.py -> build/lib/gns3server/modules/virtualbox
copying gns3server/modules/virtualbox/virtualbox_vm.py -> build/lib/gns3server/modules/virtualbox
creating build/lib/gns3server/modules/vmware
copying gns3server/modules/vmware/__init__.py -> build/lib/gns3server/modules/vmware
copying gns3server/modules/vmware/nio_vmnet.py -> build/lib/gns3server/modules/vmware
copying gns3server/modules/vmware/vmware_error.py -> build/lib/gns3server/modules/vmware
copying gns3server/modules/vmware/vmware_vm.py -> build/lib/gns3server/modules/vmware
creating build/lib/gns3server/modules/vpcs
copying gns3server/modules/vpcs/__init__.py -> build/lib/gns3server/modules/vpcs
copying gns3server/modules/vpcs/vpcs_error.py -> build/lib/gns3server/modules/vpcs
copying gns3server/modules/vpcs/vpcs_vm.py -> build/lib/gns3server/modules/vpcs
creating build/lib/gns3server/modules/dynamips/adapters
copying gns3server/modules/dynamips/adapters/__init__.py -> build/lib/gns3server/modules/dynamips/adapters
copying gns3server/modules/dynamips/adapters/adapter.py -> build/lib/gns3server/modules/dynamips/adapters
copying gns3server/modules/dynamips/adapters/c1700_mb_1fe.py -> build/lib/gns3server/modules/dynamips/adapters
copying gns3server/modules/dynamips/adapters/c1700_mb_wic1.py -> build/lib/gns3server/modules/dynamips/adapters
copying gns3server/modules/dynamips/adapters/c2600_mb_1e.py -> build/lib/gns3server/modules/dynamips/adapters
copying gns3server/modules/dynamips/adapters/c2600_mb_1fe.py -> build/lib/gns3server/modules/dynamips/adapters
copying gns3server/modules/dynamips/adapters/c2600_mb_2e.py -> build/lib/gns3server/modules/dynamips/adapters
copying gns3server/modules/dynamips/adapters/c2600_mb_2fe.py -> build/lib/gns3server/modules/dynamips/adapters
copying gns3server/modules/dynamips/adapters/c7200_io_2fe.py -> build/lib/gns3server/modules/dynamips/adapters
copying gns3server/modules/dynamips/adapters/c7200_io_fe.py -> build/lib/gns3server/modules/dynamips/adapters
copying gns3server/modules/dynamips/adapters/c7200_io_ge_e.py -> build/lib/gns3server/modules/dynamips/adapters
copying gns3server/modules/dynamips/adapters/gt96100_fe.py -> build/lib/gns3server/modules/dynamips/adapters
copying gns3server/modules/dynamips/adapters/leopard_2fe.py -> build/lib/gns3server/modules/dynamips/adapters
copying gns3server/modules/dynamips/adapters/nm_16esw.py -> build/lib/gns3server/modules/dynamips/adapters
copying gns3server/modules/dynamips/adapters/nm_1e.py -> build/lib/gns3server/modules/dynamips/adapters
copying gns3server/modules/dynamips/adapters/nm_1fe_tx.py -> build/lib/gns3server/modules/dynamips/adapters
copying gns3server/modules/dynamips/adapters/nm_4e.py -> build/lib/gns3server/modules/dynamips/adapters
copying gns3server/modules/dynamips/adapters/nm_4t.py -> build/lib/gns3server/modules/dynamips/adapters
copying gns3server/modules/dynamips/adapters/pa_2fe_tx.py -> build/lib/gns3server/modules/dynamips/adapters
copying gns3server/modules/dynamips/adapters/pa_4e.py -> build/lib/gns3server/modules/dynamips/adapters
copying gns3server/modules/dynamips/adapters/pa_4t.py -> build/lib/gns3server/modules/dynamips/adapters
copying gns3server/modules/dynamips/adapters/pa_8e.py -> build/lib/gns3server/modules/dynamips/adapters
copying gns3server/modules/dynamips/adapters/pa_8t.py -> build/lib/gns3server/modules/dynamips/adapters
copying gns3server/modules/dynamips/adapters/pa_a1.py -> build/lib/gns3server/modules/dynamips/adapters
copying gns3server/modules/dynamips/adapters/pa_fe_tx.py -> build/lib/gns3server/modules/dynamips/adapters
copying gns3server/modules/dynamips/adapters/pa_ge.py -> build/lib/gns3server/modules/dynamips/adapters
copying gns3server/modules/dynamips/adapters/pa_pos_oc3.py -> build/lib/gns3server/modules/dynamips/adapters
copying gns3server/modules/dynamips/adapters/wic_1enet.py -> build/lib/gns3server/modules/dynamips/adapters
copying gns3server/modules/dynamips/adapters/wic_1t.py -> build/lib/gns3server/modules/dynamips/adapters
copying gns3server/modules/dynamips/adapters/wic_2t.py -> build/lib/gns3server/modules/dynamips/adapters
creating build/lib/gns3server/modules/dynamips/nios
copying gns3server/modules/dynamips/nios/__init__.py -> build/lib/gns3server/modules/dynamips/nios
copying gns3server/modules/dynamips/nios/nio.py -> build/lib/gns3server/modules/dynamips/nios
copying gns3server/modules/dynamips/nios/nio_generic_ethernet.py -> build/lib/gns3server/modules/dynamips/nios
copying gns3server/modules/dynamips/nios/nio_linux_ethernet.py -> build/lib/gns3server/modules/dynamips/nios
copying gns3server/modules/dynamips/nios/nio_null.py -> build/lib/gns3server/modules/dynamips/nios
copying gns3server/modules/dynamips/nios/nio_tap.py -> build/lib/gns3server/modules/dynamips/nios
copying gns3server/modules/dynamips/nios/nio_udp.py -> build/lib/gns3server/modules/dynamips/nios
copying gns3server/modules/dynamips/nios/nio_unix.py -> build/lib/gns3server/modules/dynamips/nios
copying gns3server/modules/dynamips/nios/nio_vde.py -> build/lib/gns3server/modules/dynamips/nios
creating build/lib/gns3server/modules/dynamips/nodes
copying gns3server/modules/dynamips/nodes/__init__.py -> build/lib/gns3server/modules/dynamips/nodes
copying gns3server/modules/dynamips/nodes/atm_switch.py -> build/lib/gns3server/modules/dynamips/nodes
copying gns3server/modules/dynamips/nodes/bridge.py -> build/lib/gns3server/modules/dynamips/nodes
copying gns3server/modules/dynamips/nodes/c1700.py -> build/lib/gns3server/modules/dynamips/nodes
copying gns3server/modules/dynamips/nodes/c2600.py -> build/lib/gns3server/modules/dynamips/nodes
copying gns3server/modules/dynamips/nodes/c2691.py -> build/lib/gns3server/modules/dynamips/nodes
copying gns3server/modules/dynamips/nodes/c3600.py -> build/lib/gns3server/modules/dynamips/nodes
copying gns3server/modules/dynamips/nodes/c3725.py -> build/lib/gns3server/modules/dynamips/nodes
copying gns3server/modules/dynamips/nodes/c3745.py -> build/lib/gns3server/modules/dynamips/nodes
copying gns3server/modules/dynamips/nodes/c7200.py -> build/lib/gns3server/modules/dynamips/nodes
copying gns3server/modules/dynamips/nodes/device.py -> build/lib/gns3server/modules/dynamips/nodes
copying gns3server/modules/dynamips/nodes/ethernet_hub.py -> build/lib/gns3server/modules/dynamips/nodes
copying gns3server/modules/dynamips/nodes/ethernet_switch.py -> build/lib/gns3server/modules/dynamips/nodes
copying gns3server/modules/dynamips/nodes/frame_relay_switch.py -> build/lib/gns3server/modules/dynamips/nodes
copying gns3server/modules/dynamips/nodes/router.py -> build/lib/gns3server/modules/dynamips/nodes
creating build/lib/gns3server/modules/iou/utils
copying gns3server/modules/iou/utils/__init__.py -> build/lib/gns3server/modules/iou/utils
copying gns3server/modules/iou/utils/iou_export.py -> build/lib/gns3server/modules/iou/utils
copying gns3server/modules/iou/utils/iou_import.py -> build/lib/gns3server/modules/iou/utils
creating build/lib/gns3server/utils/asyncio
copying gns3server/utils/asyncio/__init__.py -> build/lib/gns3server/utils/asyncio
copying gns3server/utils/asyncio/raw_command_server.py -> build/lib/gns3server/utils/asyncio
copying gns3server/utils/asyncio/telnet_server.py -> build/lib/gns3server/utils/asyncio
creating build/lib/gns3server/symbols
copying gns3server/symbols/.gitkeep -> build/lib/gns3server/symbols
creating build/lib/gns3server/templates
copying gns3server/templates/index.html -> build/lib/gns3server/templates
copying gns3server/templates/layout.html -> build/lib/gns3server/templates
copying gns3server/templates/status.html -> build/lib/gns3server/templates
copying gns3server/templates/upload.html -> build/lib/gns3server/templates
creating build/lib/gns3server/modules/docker/resources
copying gns3server/modules/docker/resources/init.sh -> build/lib/gns3server/modules/docker/resources
creating build/lib/gns3server/modules/docker/resources/bin
copying gns3server/modules/docker/resources/bin/busybox -> build/lib/gns3server/modules/docker/resources/bin
creating build/lib/gns3server/modules/docker/resources/etc
creating build/lib/gns3server/modules/docker/resources/etc/udhcpc
copying gns3server/modules/docker/resources/etc/udhcpc/default.script -> build/lib/gns3server/modules/docker/resources/etc/udhcpc
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/gns3server
copying build/lib/gns3server/__init__.py -> build/bdist.linux-x86_64/egg/gns3server
copying build/lib/gns3server/__main__.py -> build/bdist.linux-x86_64/egg/gns3server
copying build/lib/gns3server/config.py -> build/bdist.linux-x86_64/egg/gns3server
copying build/lib/gns3server/crash_report.py -> build/bdist.linux-x86_64/egg/gns3server
copying build/lib/gns3server/main.py -> build/bdist.linux-x86_64/egg/gns3server
copying build/lib/gns3server/run.py -> build/bdist.linux-x86_64/egg/gns3server
copying build/lib/gns3server/server.py -> build/bdist.linux-x86_64/egg/gns3server
copying build/lib/gns3server/version.py -> build/bdist.linux-x86_64/egg/gns3server
creating build/bdist.linux-x86_64/egg/gns3server/controller
copying build/lib/gns3server/controller/__init__.py -> build/bdist.linux-x86_64/egg/gns3server/controller
creating build/bdist.linux-x86_64/egg/gns3server/handlers
copying build/lib/gns3server/handlers/__init__.py -> build/bdist.linux-x86_64/egg/gns3server/handlers
copying build/lib/gns3server/handlers/index_handler.py -> build/bdist.linux-x86_64/egg/gns3server/handlers
copying build/lib/gns3server/handlers/upload_handler.py -> build/bdist.linux-x86_64/egg/gns3server/handlers
creating build/bdist.linux-x86_64/egg/gns3server/handlers/api
copying build/lib/gns3server/handlers/api/__init__.py -> build/bdist.linux-x86_64/egg/gns3server/handlers/api
copying build/lib/gns3server/handlers/api/config_handler.py -> build/bdist.linux-x86_64/egg/gns3server/handlers/api
copying build/lib/gns3server/handlers/api/docker_handler.py -> build/bdist.linux-x86_64/egg/gns3server/handlers/api
copying build/lib/gns3server/handlers/api/dynamips_device_handler.py -> build/bdist.linux-x86_64/egg/gns3server/handlers/api
copying build/lib/gns3server/handlers/api/dynamips_vm_handler.py -> build/bdist.linux-x86_64/egg/gns3server/handlers/api
copying build/lib/gns3server/handlers/api/file_handler.py -> build/bdist.linux-x86_64/egg/gns3server/handlers/api
copying build/lib/gns3server/handlers/api/iou_handler.py -> build/bdist.linux-x86_64/egg/gns3server/handlers/api
copying build/lib/gns3server/handlers/api/network_handler.py -> build/bdist.linux-x86_64/egg/gns3server/handlers/api
copying build/lib/gns3server/handlers/api/project_handler.py -> build/bdist.linux-x86_64/egg/gns3server/handlers/api
copying build/lib/gns3server/handlers/api/qemu_handler.py -> build/bdist.linux-x86_64/egg/gns3server/handlers/api
copying build/lib/gns3server/handlers/api/server_handler.py -> build/bdist.linux-x86_64/egg/gns3server/handlers/api
copying build/lib/gns3server/handlers/api/version_handler.py -> build/bdist.linux-x86_64/egg/gns3server/handlers/api
copying build/lib/gns3server/handlers/api/virtualbox_handler.py -> build/bdist.linux-x86_64/egg/gns3server/handlers/api
copying build/lib/gns3server/handlers/api/vmware_handler.py -> build/bdist.linux-x86_64/egg/gns3server/handlers/api
copying build/lib/gns3server/handlers/api/vpcs_handler.py -> build/bdist.linux-x86_64/egg/gns3server/handlers/api
creating build/bdist.linux-x86_64/egg/gns3server/modules
copying build/lib/gns3server/modules/__init__.py -> build/bdist.linux-x86_64/egg/gns3server/modules
copying build/lib/gns3server/modules/base_manager.py -> build/bdist.linux-x86_64/egg/gns3server/modules
copying build/lib/gns3server/modules/base_vm.py -> build/bdist.linux-x86_64/egg/gns3server/modules
copying build/lib/gns3server/modules/port_manager.py -> build/bdist.linux-x86_64/egg/gns3server/modules
copying build/lib/gns3server/modules/project.py -> build/bdist.linux-x86_64/egg/gns3server/modules
copying build/lib/gns3server/modules/project_manager.py -> build/bdist.linux-x86_64/egg/gns3server/modules
copying build/lib/gns3server/modules/vm_error.py -> build/bdist.linux-x86_64/egg/gns3server/modules
creating build/bdist.linux-x86_64/egg/gns3server/modules/adapters
copying build/lib/gns3server/modules/adapters/__init__.py -> build/bdist.linux-x86_64/egg/gns3server/modules/adapters
copying build/lib/gns3server/modules/adapters/adapter.py -> build/bdist.linux-x86_64/egg/gns3server/modules/adapters
copying build/lib/gns3server/modules/adapters/ethernet_adapter.py -> build/bdist.linux-x86_64/egg/gns3server/modules/adapters
copying build/lib/gns3server/modules/adapters/serial_adapter.py -> build/bdist.linux-x86_64/egg/gns3server/modules/adapters
creating build/bdist.linux-x86_64/egg/gns3server/modules/docker
copying build/lib/gns3server/modules/docker/__init__.py -> build/bdist.linux-x86_64/egg/gns3server/modules/docker
copying build/lib/gns3server/modules/docker/docker_error.py -> build/bdist.linux-x86_64/egg/gns3server/modules/docker
copying build/lib/gns3server/modules/docker/docker_vm.py -> build/bdist.linux-x86_64/egg/gns3server/modules/docker
creating build/bdist.linux-x86_64/egg/gns3server/modules/docker/resources
copying build/lib/gns3server/modules/docker/resources/init.sh -> build/bdist.linux-x86_64/egg/gns3server/modules/docker/resources
creating build/bdist.linux-x86_64/egg/gns3server/modules/docker/resources/bin
copying build/lib/gns3server/modules/docker/resources/bin/busybox -> build/bdist.linux-x86_64/egg/gns3server/modules/docker/resources/bin
creating build/bdist.linux-x86_64/egg/gns3server/modules/docker/resources/etc
creating build/bdist.linux-x86_64/egg/gns3server/modules/docker/resources/etc/udhcpc
copying build/lib/gns3server/modules/docker/resources/etc/udhcpc/default.script -> build/bdist.linux-x86_64/egg/gns3server/modules/docker/resources/etc/udhcpc
creating build/bdist.linux-x86_64/egg/gns3server/modules/dynamips
copying build/lib/gns3server/modules/dynamips/__init__.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips
copying build/lib/gns3server/modules/dynamips/dynamips_device.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips
copying build/lib/gns3server/modules/dynamips/dynamips_error.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips
copying build/lib/gns3server/modules/dynamips/dynamips_hypervisor.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips
copying build/lib/gns3server/modules/dynamips/dynamips_vm.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips
copying build/lib/gns3server/modules/dynamips/hypervisor.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips
creating build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters
copying build/lib/gns3server/modules/dynamips/adapters/__init__.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters
copying build/lib/gns3server/modules/dynamips/adapters/adapter.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters
copying build/lib/gns3server/modules/dynamips/adapters/c1700_mb_1fe.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters
copying build/lib/gns3server/modules/dynamips/adapters/c1700_mb_wic1.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters
copying build/lib/gns3server/modules/dynamips/adapters/c2600_mb_1e.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters
copying build/lib/gns3server/modules/dynamips/adapters/c2600_mb_1fe.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters
copying build/lib/gns3server/modules/dynamips/adapters/c2600_mb_2e.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters
copying build/lib/gns3server/modules/dynamips/adapters/c2600_mb_2fe.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters
copying build/lib/gns3server/modules/dynamips/adapters/c7200_io_2fe.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters
copying build/lib/gns3server/modules/dynamips/adapters/c7200_io_fe.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters
copying build/lib/gns3server/modules/dynamips/adapters/c7200_io_ge_e.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters
copying build/lib/gns3server/modules/dynamips/adapters/gt96100_fe.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters
copying build/lib/gns3server/modules/dynamips/adapters/leopard_2fe.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters
copying build/lib/gns3server/modules/dynamips/adapters/nm_16esw.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters
copying build/lib/gns3server/modules/dynamips/adapters/nm_1e.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters
copying build/lib/gns3server/modules/dynamips/adapters/nm_1fe_tx.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters
copying build/lib/gns3server/modules/dynamips/adapters/nm_4e.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters
copying build/lib/gns3server/modules/dynamips/adapters/nm_4t.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters
copying build/lib/gns3server/modules/dynamips/adapters/pa_2fe_tx.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters
copying build/lib/gns3server/modules/dynamips/adapters/pa_4e.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters
copying build/lib/gns3server/modules/dynamips/adapters/pa_4t.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters
copying build/lib/gns3server/modules/dynamips/adapters/pa_8e.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters
copying build/lib/gns3server/modules/dynamips/adapters/pa_8t.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters
copying build/lib/gns3server/modules/dynamips/adapters/pa_a1.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters
copying build/lib/gns3server/modules/dynamips/adapters/pa_fe_tx.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters
copying build/lib/gns3server/modules/dynamips/adapters/pa_ge.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters
copying build/lib/gns3server/modules/dynamips/adapters/pa_pos_oc3.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters
copying build/lib/gns3server/modules/dynamips/adapters/wic_1enet.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters
copying build/lib/gns3server/modules/dynamips/adapters/wic_1t.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters
copying build/lib/gns3server/modules/dynamips/adapters/wic_2t.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters
creating build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/nios
copying build/lib/gns3server/modules/dynamips/nios/__init__.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/nios
copying build/lib/gns3server/modules/dynamips/nios/nio.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/nios
copying build/lib/gns3server/modules/dynamips/nios/nio_generic_ethernet.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/nios
copying build/lib/gns3server/modules/dynamips/nios/nio_linux_ethernet.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/nios
copying build/lib/gns3server/modules/dynamips/nios/nio_null.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/nios
copying build/lib/gns3server/modules/dynamips/nios/nio_tap.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/nios
copying build/lib/gns3server/modules/dynamips/nios/nio_udp.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/nios
copying build/lib/gns3server/modules/dynamips/nios/nio_unix.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/nios
copying build/lib/gns3server/modules/dynamips/nios/nio_vde.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/nios
creating build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/nodes
copying build/lib/gns3server/modules/dynamips/nodes/__init__.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/nodes
copying build/lib/gns3server/modules/dynamips/nodes/atm_switch.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/nodes
copying build/lib/gns3server/modules/dynamips/nodes/bridge.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/nodes
copying build/lib/gns3server/modules/dynamips/nodes/c1700.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/nodes
copying build/lib/gns3server/modules/dynamips/nodes/c2600.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/nodes
copying build/lib/gns3server/modules/dynamips/nodes/c2691.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/nodes
copying build/lib/gns3server/modules/dynamips/nodes/c3600.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/nodes
copying build/lib/gns3server/modules/dynamips/nodes/c3725.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/nodes
copying build/lib/gns3server/modules/dynamips/nodes/c3745.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/nodes
copying build/lib/gns3server/modules/dynamips/nodes/c7200.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/nodes
copying build/lib/gns3server/modules/dynamips/nodes/device.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/nodes
copying build/lib/gns3server/modules/dynamips/nodes/ethernet_hub.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/nodes
copying build/lib/gns3server/modules/dynamips/nodes/ethernet_switch.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/nodes
copying build/lib/gns3server/modules/dynamips/nodes/frame_relay_switch.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/nodes
copying build/lib/gns3server/modules/dynamips/nodes/router.py -> build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/nodes
creating build/bdist.linux-x86_64/egg/gns3server/modules/iou
copying build/lib/gns3server/modules/iou/__init__.py -> build/bdist.linux-x86_64/egg/gns3server/modules/iou
copying build/lib/gns3server/modules/iou/iou_error.py -> build/bdist.linux-x86_64/egg/gns3server/modules/iou
copying build/lib/gns3server/modules/iou/iou_vm.py -> build/bdist.linux-x86_64/egg/gns3server/modules/iou
copying build/lib/gns3server/modules/iou/ioucon.py -> build/bdist.linux-x86_64/egg/gns3server/modules/iou
creating build/bdist.linux-x86_64/egg/gns3server/modules/iou/utils
copying build/lib/gns3server/modules/iou/utils/__init__.py -> build/bdist.linux-x86_64/egg/gns3server/modules/iou/utils
copying build/lib/gns3server/modules/iou/utils/iou_export.py -> build/bdist.linux-x86_64/egg/gns3server/modules/iou/utils
copying build/lib/gns3server/modules/iou/utils/iou_import.py -> build/bdist.linux-x86_64/egg/gns3server/modules/iou/utils
creating build/bdist.linux-x86_64/egg/gns3server/modules/nios
copying build/lib/gns3server/modules/nios/__init__.py -> build/bdist.linux-x86_64/egg/gns3server/modules/nios
copying build/lib/gns3server/modules/nios/nio.py -> build/bdist.linux-x86_64/egg/gns3server/modules/nios
copying build/lib/gns3server/modules/nios/nio_generic_ethernet.py -> build/bdist.linux-x86_64/egg/gns3server/modules/nios
copying build/lib/gns3server/modules/nios/nio_nat.py -> build/bdist.linux-x86_64/egg/gns3server/modules/nios
copying build/lib/gns3server/modules/nios/nio_tap.py -> build/bdist.linux-x86_64/egg/gns3server/modules/nios
copying build/lib/gns3server/modules/nios/nio_udp.py -> build/bdist.linux-x86_64/egg/gns3server/modules/nios
creating build/bdist.linux-x86_64/egg/gns3server/modules/qemu
copying build/lib/gns3server/modules/qemu/__init__.py -> build/bdist.linux-x86_64/egg/gns3server/modules/qemu
copying build/lib/gns3server/modules/qemu/qcow2.py -> build/bdist.linux-x86_64/egg/gns3server/modules/qemu
copying build/lib/gns3server/modules/qemu/qemu_error.py -> build/bdist.linux-x86_64/egg/gns3server/modules/qemu
copying build/lib/gns3server/modules/qemu/qemu_vm.py -> build/bdist.linux-x86_64/egg/gns3server/modules/qemu
creating build/bdist.linux-x86_64/egg/gns3server/modules/virtualbox
copying build/lib/gns3server/modules/virtualbox/__init__.py -> build/bdist.linux-x86_64/egg/gns3server/modules/virtualbox
copying build/lib/gns3server/modules/virtualbox/virtualbox_error.py -> build/bdist.linux-x86_64/egg/gns3server/modules/virtualbox
copying build/lib/gns3server/modules/virtualbox/virtualbox_vm.py -> build/bdist.linux-x86_64/egg/gns3server/modules/virtualbox
creating build/bdist.linux-x86_64/egg/gns3server/modules/vmware
copying build/lib/gns3server/modules/vmware/__init__.py -> build/bdist.linux-x86_64/egg/gns3server/modules/vmware
copying build/lib/gns3server/modules/vmware/nio_vmnet.py -> build/bdist.linux-x86_64/egg/gns3server/modules/vmware
copying build/lib/gns3server/modules/vmware/vmware_error.py -> build/bdist.linux-x86_64/egg/gns3server/modules/vmware
copying build/lib/gns3server/modules/vmware/vmware_vm.py -> build/bdist.linux-x86_64/egg/gns3server/modules/vmware
creating build/bdist.linux-x86_64/egg/gns3server/modules/vpcs
copying build/lib/gns3server/modules/vpcs/__init__.py -> build/bdist.linux-x86_64/egg/gns3server/modules/vpcs
copying build/lib/gns3server/modules/vpcs/vpcs_error.py -> build/bdist.linux-x86_64/egg/gns3server/modules/vpcs
copying build/lib/gns3server/modules/vpcs/vpcs_vm.py -> build/bdist.linux-x86_64/egg/gns3server/modules/vpcs
creating build/bdist.linux-x86_64/egg/gns3server/schemas
copying build/lib/gns3server/schemas/__init__.py -> build/bdist.linux-x86_64/egg/gns3server/schemas
copying build/lib/gns3server/schemas/docker.py -> build/bdist.linux-x86_64/egg/gns3server/schemas
copying build/lib/gns3server/schemas/dynamips_device.py -> build/bdist.linux-x86_64/egg/gns3server/schemas
copying build/lib/gns3server/schemas/dynamips_vm.py -> build/bdist.linux-x86_64/egg/gns3server/schemas
copying build/lib/gns3server/schemas/file.py -> build/bdist.linux-x86_64/egg/gns3server/schemas
copying build/lib/gns3server/schemas/iou.py -> build/bdist.linux-x86_64/egg/gns3server/schemas
copying build/lib/gns3server/schemas/nio.py -> build/bdist.linux-x86_64/egg/gns3server/schemas
copying build/lib/gns3server/schemas/project.py -> build/bdist.linux-x86_64/egg/gns3server/schemas
copying build/lib/gns3server/schemas/qemu.py -> build/bdist.linux-x86_64/egg/gns3server/schemas
copying build/lib/gns3server/schemas/version.py -> build/bdist.linux-x86_64/egg/gns3server/schemas
copying build/lib/gns3server/schemas/virtualbox.py -> build/bdist.linux-x86_64/egg/gns3server/schemas
copying build/lib/gns3server/schemas/vm.py -> build/bdist.linux-x86_64/egg/gns3server/schemas
copying build/lib/gns3server/schemas/vmware.py -> build/bdist.linux-x86_64/egg/gns3server/schemas
copying build/lib/gns3server/schemas/vpcs.py -> build/bdist.linux-x86_64/egg/gns3server/schemas
creating build/bdist.linux-x86_64/egg/gns3server/ubridge
copying build/lib/gns3server/ubridge/__init__.py -> build/bdist.linux-x86_64/egg/gns3server/ubridge
copying build/lib/gns3server/ubridge/hypervisor.py -> build/bdist.linux-x86_64/egg/gns3server/ubridge
copying build/lib/gns3server/ubridge/ubridge_error.py -> build/bdist.linux-x86_64/egg/gns3server/ubridge
copying build/lib/gns3server/ubridge/ubridge_hypervisor.py -> build/bdist.linux-x86_64/egg/gns3server/ubridge
creating build/bdist.linux-x86_64/egg/gns3server/utils
copying build/lib/gns3server/utils/__init__.py -> build/bdist.linux-x86_64/egg/gns3server/utils
copying build/lib/gns3server/utils/get_resource.py -> build/bdist.linux-x86_64/egg/gns3server/utils
copying build/lib/gns3server/utils/images.py -> build/bdist.linux-x86_64/egg/gns3server/utils
copying build/lib/gns3server/utils/interfaces.py -> build/bdist.linux-x86_64/egg/gns3server/utils
copying build/lib/gns3server/utils/telnet_server.py -> build/bdist.linux-x86_64/egg/gns3server/utils
copying build/lib/gns3server/utils/vmnet.py -> build/bdist.linux-x86_64/egg/gns3server/utils
creating build/bdist.linux-x86_64/egg/gns3server/utils/asyncio
copying build/lib/gns3server/utils/asyncio/__init__.py -> build/bdist.linux-x86_64/egg/gns3server/utils/asyncio
copying build/lib/gns3server/utils/asyncio/raw_command_server.py -> build/bdist.linux-x86_64/egg/gns3server/utils/asyncio
copying build/lib/gns3server/utils/asyncio/telnet_server.py -> build/bdist.linux-x86_64/egg/gns3server/utils/asyncio
creating build/bdist.linux-x86_64/egg/gns3server/web
copying build/lib/gns3server/web/__init__.py -> build/bdist.linux-x86_64/egg/gns3server/web
copying build/lib/gns3server/web/documentation.py -> build/bdist.linux-x86_64/egg/gns3server/web
copying build/lib/gns3server/web/logger.py -> build/bdist.linux-x86_64/egg/gns3server/web
copying build/lib/gns3server/web/response.py -> build/bdist.linux-x86_64/egg/gns3server/web
copying build/lib/gns3server/web/route.py -> build/bdist.linux-x86_64/egg/gns3server/web
creating build/bdist.linux-x86_64/egg/gns3server/symbols
copying build/lib/gns3server/symbols/.gitkeep -> build/bdist.linux-x86_64/egg/gns3server/symbols
creating build/bdist.linux-x86_64/egg/gns3server/templates
copying build/lib/gns3server/templates/index.html -> build/bdist.linux-x86_64/egg/gns3server/templates
copying build/lib/gns3server/templates/layout.html -> build/bdist.linux-x86_64/egg/gns3server/templates
copying build/lib/gns3server/templates/status.html -> build/bdist.linux-x86_64/egg/gns3server/templates
copying build/lib/gns3server/templates/upload.html -> build/bdist.linux-x86_64/egg/gns3server/templates
byte-compiling build/bdist.linux-x86_64/egg/gns3server/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/__main__.py to __main__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/config.py to config.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/crash_report.py to crash_report.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/main.py to main.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/run.py to run.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/server.py to server.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/version.py to version.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/controller/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/handlers/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/handlers/index_handler.py to index_handler.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/handlers/upload_handler.py to upload_handler.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/handlers/api/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/handlers/api/config_handler.py to config_handler.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/handlers/api/docker_handler.py to docker_handler.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/handlers/api/dynamips_device_handler.py to dynamips_device_handler.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/handlers/api/dynamips_vm_handler.py to dynamips_vm_handler.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/handlers/api/file_handler.py to file_handler.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/handlers/api/iou_handler.py to iou_handler.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/handlers/api/network_handler.py to network_handler.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/handlers/api/project_handler.py to project_handler.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/handlers/api/qemu_handler.py to qemu_handler.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/handlers/api/server_handler.py to server_handler.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/handlers/api/version_handler.py to version_handler.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/handlers/api/virtualbox_handler.py to virtualbox_handler.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/handlers/api/vmware_handler.py to vmware_handler.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/handlers/api/vpcs_handler.py to vpcs_handler.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/base_manager.py to base_manager.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/base_vm.py to base_vm.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/port_manager.py to port_manager.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/project.py to project.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/project_manager.py to project_manager.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/vm_error.py to vm_error.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/adapters/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/adapters/adapter.py to adapter.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/adapters/ethernet_adapter.py to ethernet_adapter.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/adapters/serial_adapter.py to serial_adapter.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/docker/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/docker/docker_error.py to docker_error.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/docker/docker_vm.py to docker_vm.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/dynamips_device.py to dynamips_device.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/dynamips_error.py to dynamips_error.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/dynamips_hypervisor.py to dynamips_hypervisor.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/dynamips_vm.py to dynamips_vm.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/hypervisor.py to hypervisor.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters/adapter.py to adapter.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters/c1700_mb_1fe.py to c1700_mb_1fe.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters/c1700_mb_wic1.py to c1700_mb_wic1.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters/c2600_mb_1e.py to c2600_mb_1e.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters/c2600_mb_1fe.py to c2600_mb_1fe.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters/c2600_mb_2e.py to c2600_mb_2e.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters/c2600_mb_2fe.py to c2600_mb_2fe.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters/c7200_io_2fe.py to c7200_io_2fe.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters/c7200_io_fe.py to c7200_io_fe.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters/c7200_io_ge_e.py to c7200_io_ge_e.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters/gt96100_fe.py to gt96100_fe.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters/leopard_2fe.py to leopard_2fe.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters/nm_16esw.py to nm_16esw.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters/nm_1e.py to nm_1e.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters/nm_1fe_tx.py to nm_1fe_tx.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters/nm_4e.py to nm_4e.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters/nm_4t.py to nm_4t.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters/pa_2fe_tx.py to pa_2fe_tx.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters/pa_4e.py to pa_4e.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters/pa_4t.py to pa_4t.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters/pa_8e.py to pa_8e.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters/pa_8t.py to pa_8t.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters/pa_a1.py to pa_a1.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters/pa_fe_tx.py to pa_fe_tx.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters/pa_ge.py to pa_ge.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters/pa_pos_oc3.py to pa_pos_oc3.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters/wic_1enet.py to wic_1enet.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters/wic_1t.py to wic_1t.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/adapters/wic_2t.py to wic_2t.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/nios/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/nios/nio.py to nio.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/nios/nio_generic_ethernet.py to nio_generic_ethernet.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/nios/nio_linux_ethernet.py to nio_linux_ethernet.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/nios/nio_null.py to nio_null.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/nios/nio_tap.py to nio_tap.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/nios/nio_udp.py to nio_udp.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/nios/nio_unix.py to nio_unix.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/nios/nio_vde.py to nio_vde.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/nodes/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/nodes/atm_switch.py to atm_switch.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/nodes/bridge.py to bridge.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/nodes/c1700.py to c1700.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/nodes/c2600.py to c2600.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/nodes/c2691.py to c2691.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/nodes/c3600.py to c3600.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/nodes/c3725.py to c3725.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/nodes/c3745.py to c3745.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/nodes/c7200.py to c7200.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/nodes/device.py to device.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/nodes/ethernet_hub.py to ethernet_hub.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/nodes/ethernet_switch.py to ethernet_switch.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/nodes/frame_relay_switch.py to frame_relay_switch.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/dynamips/nodes/router.py to router.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/iou/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/iou/iou_error.py to iou_error.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/iou/iou_vm.py to iou_vm.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/iou/ioucon.py to ioucon.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/iou/utils/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/iou/utils/iou_export.py to iou_export.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/iou/utils/iou_import.py to iou_import.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/nios/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/nios/nio.py to nio.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/nios/nio_generic_ethernet.py to nio_generic_ethernet.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/nios/nio_nat.py to nio_nat.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/nios/nio_tap.py to nio_tap.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/nios/nio_udp.py to nio_udp.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/qemu/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/qemu/qcow2.py to qcow2.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/qemu/qemu_error.py to qemu_error.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/qemu/qemu_vm.py to qemu_vm.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/virtualbox/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/virtualbox/virtualbox_error.py to virtualbox_error.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/virtualbox/virtualbox_vm.py to virtualbox_vm.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/vmware/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/vmware/nio_vmnet.py to nio_vmnet.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/vmware/vmware_error.py to vmware_error.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/vmware/vmware_vm.py to vmware_vm.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/vpcs/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/vpcs/vpcs_error.py to vpcs_error.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/modules/vpcs/vpcs_vm.py to vpcs_vm.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/schemas/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/schemas/docker.py to docker.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/schemas/dynamips_device.py to dynamips_device.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/schemas/dynamips_vm.py to dynamips_vm.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/schemas/file.py to file.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/schemas/iou.py to iou.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/schemas/nio.py to nio.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/schemas/project.py to project.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/schemas/qemu.py to qemu.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/schemas/version.py to version.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/schemas/virtualbox.py to virtualbox.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/schemas/vm.py to vm.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/schemas/vmware.py to vmware.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/schemas/vpcs.py to vpcs.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/ubridge/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/ubridge/hypervisor.py to hypervisor.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/ubridge/ubridge_error.py to ubridge_error.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/ubridge/ubridge_hypervisor.py to ubridge_hypervisor.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/utils/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/utils/get_resource.py to get_resource.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/utils/images.py to images.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/utils/interfaces.py to interfaces.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/utils/telnet_server.py to telnet_server.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/utils/vmnet.py to vmnet.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/utils/asyncio/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/utils/asyncio/raw_command_server.py to raw_command_server.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/utils/asyncio/telnet_server.py to telnet_server.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/web/__init__.py to __init__.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/web/documentation.py to documentation.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/web/logger.py to logger.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/web/response.py to response.cpython-35.pyc
byte-compiling build/bdist.linux-x86_64/egg/gns3server/web/route.py to route.cpython-35.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying gns3_server.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying gns3_server.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying gns3_server.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying gns3_server.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying gns3_server.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying gns3_server.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
gns3server.__pycache__.server.cpython-35: module references __file__
creating dist
creating 'dist/gns3_server-1.5.4.dev1-py3.5.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing gns3_server-1.5.4.dev1-py3.5.egg
creating /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/gns3_server-1.5.4.dev1-py3.5.egg
Extracting gns3_server-1.5.4.dev1-py3.5.egg to /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages
Adding gns3-server 1.5.4.dev1 to easy-install.pth file
Installing gns3vmnet script to /home/travis/virtualenv/python3.5.2/bin
Installing gns3server script to /home/travis/virtualenv/python3.5.2/bin

Installed /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/gns3_server-1.5.4.dev1-py3.5.egg
Processing dependencies for gns3-server==1.5.4.dev1
Searching for zipstream>=1.1.4
Reading https://pypi.python.org/simple/zipstream/
Downloading https://pypi.python.org/packages/1a/a4/58f0709cef999db1539960aa2ae77100dc800ebb8abb7afc97a1398dfb2f/zipstream-1.1.4.tar.gz#md5=9d3755748c15eb622604e99dddac3652
Best match: zipstream 1.1.4
Processing zipstream-1.1.4.tar.gz
Writing /tmp/easy_install-1twrdd3k/zipstream-1.1.4/setup.cfg
Running zipstream-1.1.4/setup.py -q bdist_egg --dist-dir /tmp/easy_install-1twrdd3k/zipstream-1.1.4/egg-dist-tmp-2kcvkkxc
zip_safe flag not set; analyzing archive contents...
Moving zipstream-1.1.4-py3.5.egg to /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages
Adding zipstream 1.1.4 to easy-install.pth file

Installed /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/zipstream-1.1.4-py3.5.egg
Searching for psutil>=3.0.0
Reading https://pypi.python.org/simple/psutil/
Downloading https://pypi.python.org/packages/57/93/47a2e3befaf194ccc3d05ffbcba2cdcdd22a231100ef7e4cf63f085c900b/psutil-5.2.2.tar.gz#md5=bb98d48796cd76d9ccee871aad720f9c
Best match: psutil 5.2.2
Processing psutil-5.2.2.tar.gz
Writing /tmp/easy_install-zv56fmpp/psutil-5.2.2/setup.cfg
Running psutil-5.2.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-zv56fmpp/psutil-5.2.2/egg-dist-tmp-3pqycv83
warning: manifest_maker: MANIFEST.in, line 14: 'recursive-include' expects <dir> <pattern1> <pattern2> ...

warning: no previously-included files matching '*' found under directory 'docs/_build'
warning: no previously-included files matching '*' found under directory '.ci'
creating /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/psutil-5.2.2-py3.5-linux-x86_64.egg
Extracting psutil-5.2.2-py3.5-linux-x86_64.egg to /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages
Adding psutil 5.2.2 to easy-install.pth file

Installed /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/psutil-5.2.2-py3.5-linux-x86_64.egg
Searching for raven>=5.23.0
Reading https://pypi.python.org/simple/raven/
Downloading https://pypi.python.org/packages/0c/e6/a6e2a56e9f80cc7fd7a466c7c8d353780204c5aeeb07037e588d9dc21947/raven-6.0.0.zip#md5=28063ed6ebb0847aa5f493b3abfff92e
Best match: raven 6.0.0
Processing raven-6.0.0.zip
Writing /tmp/easy_install-u04rwovt/raven-6.0.0/setup.cfg
Running raven-6.0.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-u04rwovt/raven-6.0.0/egg-dist-tmp-bu0hmsqn
warning: no files found matching '*.txt'
warning: no previously-included files matching '*~' found anywhere in distribution
creating /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/raven-6.0.0-py3.5.egg
Extracting raven-6.0.0-py3.5.egg to /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages
Adding raven 6.0.0 to easy-install.pth file
Installing raven script to /home/travis/virtualenv/python3.5.2/bin

Installed /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/raven-6.0.0-py3.5.egg
Searching for Jinja2>=2.7.3
Reading https://pypi.python.org/simple/Jinja2/
Downloading https://pypi.python.org/packages/90/61/f820ff0076a2599dd39406dcb858ecb239438c02ce706c8e91131ab9c7f1/Jinja2-2.9.6.tar.gz#md5=6411537324b4dba0956aaa8109f3c77b
Best match: Jinja2 2.9.6
Processing Jinja2-2.9.6.tar.gz
Writing /tmp/easy_install-ng446j_z/Jinja2-2.9.6/setup.cfg
Running Jinja2-2.9.6/setup.py -q bdist_egg --dist-dir /tmp/easy_install-ng446j_z/Jinja2-2.9.6/egg-dist-tmp-swhf6dd0
warning: no files found matching 'run-tests.py'
warning: no files found matching '*' under directory 'custom_fixers'
warning: no files found matching '*' under directory 'jinja2/testsuite/res'
warning: no previously-included files matching '*' found under directory 'docs/_build'
warning: no previously-included files matching '*.pyc' found under directory 'jinja2'
warning: no previously-included files matching '*.pyc' found under directory 'docs'
warning: no previously-included files matching '*.pyo' found under directory 'jinja2'
warning: no previously-included files matching '*.pyo' found under directory 'docs'
  File "build/bdist.linux-x86_64/egg/jinja2/asyncfilters.py", line 24
    yield item
             ^
SyntaxError: 'yield' inside async function

  File "build/bdist.linux-x86_64/egg/jinja2/asyncsupport.py", line 35
    yield event
              ^
SyntaxError: 'yield' inside async function

creating /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/Jinja2-2.9.6-py3.5.egg
Extracting Jinja2-2.9.6-py3.5.egg to /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/Jinja2-2.9.6-py3.5.egg/jinja2/asyncfilters.py", line 24
    yield item
             ^
SyntaxError: 'yield' inside async function

  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/Jinja2-2.9.6-py3.5.egg/jinja2/asyncsupport.py", line 35
    yield event
              ^
SyntaxError: 'yield' inside async function

Adding Jinja2 2.9.6 to easy-install.pth file

Installed /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/Jinja2-2.9.6-py3.5.egg
Searching for typing>=3.5.3.0
Reading https://pypi.python.org/simple/typing/
Downloading https://pypi.python.org/packages/17/75/3698d7992a828ad6d7be99c0a888b75ed173a9280e53dbae67326029b60e/typing-3.6.1.tar.gz#md5=3fec97415bae6f742fb3c3013dedeb89
Best match: typing 3.6.1
Processing typing-3.6.1.tar.gz
Writing /tmp/easy_install-p5obz3wg/typing-3.6.1/setup.cfg
Running typing-3.6.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-p5obz3wg/typing-3.6.1/egg-dist-tmp-roc2fvbr
zip_safe flag not set; analyzing archive contents...
Moving typing-3.6.1-py3.5.egg to /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages
Adding typing 3.6.1 to easy-install.pth file

Installed /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/typing-3.6.1-py3.5.egg
Searching for yarl<0.10,>=0.9.8
Reading https://pypi.python.org/simple/yarl/
Downloading https://pypi.python.org/packages/66/2e/646e7da82260ad1dce86ebeed0befbd487941b7aa61ee2291fa47aa71bf4/yarl-0.9.8.tar.gz#md5=055d1386dfc269c37785508b07d82665
Best match: yarl 0.9.8
Processing yarl-0.9.8.tar.gz
Writing /tmp/easy_install-j0qm0a77/yarl-0.9.8/setup.cfg
Running yarl-0.9.8/setup.py -q bdist_egg --dist-dir /tmp/easy_install-j0qm0a77/yarl-0.9.8/egg-dist-tmp-2lyhpyuf
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.cache' found anywhere in distribution
warning: no previously-included files found matching 'yarl/_quoting.html'
warning: no previously-included files found matching 'yarl/_quoting.*.so'
warning: no previously-included files found matching 'yarl/_quoting.pyd'
warning: no previously-included files found matching 'yarl/_quoting.*.pyd'
no previously-included directories found matching 'docs/_build'
zip_safe flag not set; analyzing archive contents...
yarl.__pycache__._quoting.cpython-35: module references __file__
creating /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/yarl-0.9.8-py3.5-linux-x86_64.egg
Extracting yarl-0.9.8-py3.5-linux-x86_64.egg to /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages
Adding yarl 0.9.8 to easy-install.pth file

Installed /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/yarl-0.9.8-py3.5-linux-x86_64.egg
Searching for aiohttp-cors==0.5.1
Reading https://pypi.python.org/simple/aiohttp-cors/
Downloading https://pypi.python.org/packages/7f/49/03a264b3791717bbfa6ee79b1bf46a417592b361223d1704c694d6e5e81b/aiohttp-cors-0.5.1.tar.gz#md5=0ea7e6a2401b140009e58b791dfbbaca
Best match: aiohttp-cors 0.5.1
Processing aiohttp-cors-0.5.1.tar.gz
Writing /tmp/easy_install-uftceo9j/aiohttp-cors-0.5.1/setup.cfg
Running aiohttp-cors-0.5.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-uftceo9j/aiohttp-cors-0.5.1/egg-dist-tmp-hn0mm9qx
zip_safe flag not set; analyzing archive contents...
Moving aiohttp_cors-0.5.1-py3.5.egg to /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages
Adding aiohttp-cors 0.5.1 to easy-install.pth file

Installed /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp_cors-0.5.1-py3.5.egg
Searching for aiohttp<=1.4.0,>=1.3.5
Reading https://pypi.python.org/simple/aiohttp/
Downloading https://pypi.python.org/packages/e9/08/721f2e99f4ed694335f533a2910b4c75b1b37a376fe65da07903e0bbe1d2/aiohttp-1.3.5.tar.gz#md5=fac473aa71b5e49a6978b5bcc393a7ef
Best match: aiohttp 1.3.5
Processing aiohttp-1.3.5.tar.gz
Writing /tmp/easy_install-oth6wabt/aiohttp-1.3.5/setup.cfg
Running aiohttp-1.3.5/setup.py -q bdist_egg --dist-dir /tmp/easy_install-oth6wabt/aiohttp-1.3.5/egg-dist-tmp-sv1l2dla
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files found matching 'aiohttp/_multidict.html'
warning: no previously-included files found matching 'aiohttp/_multidict.*.so'
warning: no previously-included files found matching 'aiohttp/_multidict.pyd'
warning: no previously-included files found matching 'aiohttp/_multidict.*.pyd'
warning: no previously-included files found matching 'aiohttp/_websocket.html'
warning: no previously-included files found matching 'aiohttp/_websocket.*.so'
warning: no previously-included files found matching 'aiohttp/_websocket.pyd'
warning: no previously-included files found matching 'aiohttp/_websocket.*.pyd'
no previously-included directories found matching 'docs/_build'
zip_safe flag not set; analyzing archive contents...
aiohttp.__pycache__._websocket.cpython-35: module references __file__
creating /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg
Extracting aiohttp-1.3.5-py3.5-linux-x86_64.egg to /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages
Adding aiohttp 1.3.5 to easy-install.pth file

Installed /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg
Searching for jsonschema>=2.4.0
Reading https://pypi.python.org/simple/jsonschema/
Downloading https://pypi.python.org/packages/58/b9/171dbb07e18c6346090a37f03c7e74410a1a56123f847efed59af260a298/jsonschema-2.6.0.tar.gz#md5=50c6b69a373a8b55ff1e0ec6e78f13f4
Best match: jsonschema 2.6.0
Processing jsonschema-2.6.0.tar.gz
Writing /tmp/easy_install-tuxmbfes/jsonschema-2.6.0/setup.cfg
Running jsonschema-2.6.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-tuxmbfes/jsonschema-2.6.0/egg-dist-tmp-vztcrhip
zip_safe flag not set; analyzing archive contents...

Installed /tmp/easy_install-tuxmbfes/jsonschema-2.6.0/.eggs/vcversioner-2.16.0.0-py3.5.egg
zip_safe flag not set; analyzing archive contents...
jsonschema.tests.__pycache__.test_jsonschema_test_suite.cpython-35: module references __file__
creating /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/jsonschema-2.6.0-py3.5.egg
Extracting jsonschema-2.6.0-py3.5.egg to /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages
Adding jsonschema 2.6.0 to easy-install.pth file
Installing jsonschema script to /home/travis/virtualenv/python3.5.2/bin

Installed /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/jsonschema-2.6.0-py3.5.egg
Searching for MarkupSafe>=0.23
Reading https://pypi.python.org/simple/MarkupSafe/
Downloading https://pypi.python.org/packages/4d/de/32d741db316d8fdb7680822dd37001ef7a448255de9699ab4bfcbdf4172b/MarkupSafe-1.0.tar.gz#md5=2fcedc9284d50e577b5192e8e3578355
Best match: MarkupSafe 1.0
Processing MarkupSafe-1.0.tar.gz
Writing /tmp/easy_install-aadthruf/MarkupSafe-1.0/setup.cfg
Running MarkupSafe-1.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-aadthruf/MarkupSafe-1.0/egg-dist-tmp-qtcxxlaa
creating /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/MarkupSafe-1.0-py3.5-linux-x86_64.egg
Extracting MarkupSafe-1.0-py3.5-linux-x86_64.egg to /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages
Adding MarkupSafe 1.0 to easy-install.pth file

Installed /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/MarkupSafe-1.0-py3.5-linux-x86_64.egg
Searching for multidict>=2.0
Reading https://pypi.python.org/simple/multidict/
Downloading https://pypi.python.org/packages/2a/df/eaea73e46a58fd780c35ecc304ca42364fa3c1f4cd03568ed33b9d2c7547/multidict-2.1.4.tar.gz#md5=051d92edec87fd98e43ea83f3ce6072d
Best match: multidict 2.1.4
Processing multidict-2.1.4.tar.gz
Writing /tmp/easy_install-5b3zii2s/multidict-2.1.4/setup.cfg
Running multidict-2.1.4/setup.py -q bdist_egg --dist-dir /tmp/easy_install-5b3zii2s/multidict-2.1.4/egg-dist-tmp-wvc1rckj
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files found matching 'multidict/_multidict.html'
warning: no previously-included files found matching 'multidict/_multidict.*.so'
warning: no previously-included files found matching 'multidict/_multidict.pyd'
warning: no previously-included files found matching 'multidict/_multidict.*.pyd'
no previously-included directories found matching 'docs/_build'
zip_safe flag not set; analyzing archive contents...
multidict.__pycache__._multidict.cpython-35: module references __file__
creating /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/multidict-2.1.4-py3.5-linux-x86_64.egg
Extracting multidict-2.1.4-py3.5-linux-x86_64.egg to /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages
Adding multidict 2.1.4 to easy-install.pth file

Installed /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/multidict-2.1.4-py3.5-linux-x86_64.egg
Searching for async_timeout>=1.1.0
Reading https://pypi.python.org/simple/async_timeout/
Downloading https://pypi.python.org/packages/55/67/3870ef0811ee3e40b67d776b3144743f34a2a2d094690af83a1c5390806e/async-timeout-1.2.0.tar.gz#md5=b9fc198be2e415e6786da596091abe40
Best match: async-timeout 1.2.0
Processing async-timeout-1.2.0.tar.gz
Writing /tmp/easy_install-96rmddni/async-timeout-1.2.0/setup.cfg
Running async-timeout-1.2.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-96rmddni/async-timeout-1.2.0/egg-dist-tmp-pqpk7wnt
zip_safe flag not set; analyzing archive contents...

Installed /tmp/easy_install-96rmddni/async-timeout-1.2.0/.eggs/pytest_runner-2.11.1-py3.5.egg
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.cache' found anywhere in distribution
zip_safe flag not set; analyzing archive contents...
Moving async_timeout-1.2.0-py3.5.egg to /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages
Adding async-timeout 1.2.0 to easy-install.pth file

Installed /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/async_timeout-1.2.0-py3.5.egg
Searching for chardet
Reading https://pypi.python.org/simple/chardet/
Downloading https://pypi.python.org/packages/91/05/28f23094cdf1410fb03533f0d71e6b4aad3c504100e83b8cea6fc899552c/chardet-3.0.2.tar.gz#md5=96e364abdbde20b5f6dbbe2ad9d54d04
Best match: chardet 3.0.2
Processing chardet-3.0.2.tar.gz
Writing /tmp/easy_install-oavryq_f/chardet-3.0.2/setup.cfg
Running chardet-3.0.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-oavryq_f/chardet-3.0.2/egg-dist-tmp-28zrqb2w
zip_safe flag not set; analyzing archive contents...

Installed /tmp/easy_install-oavryq_f/chardet-3.0.2/.eggs/pytest_runner-2.11.1-py3.5.egg
warning: no files found matching 'requirements.txt'
zip_safe flag not set; analyzing archive contents...
Moving chardet-3.0.2-py3.5.egg to /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages
Adding chardet 3.0.2 to easy-install.pth file
Installing chardetect script to /home/travis/virtualenv/python3.5.2/bin

Installed /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/chardet-3.0.2-py3.5.egg
Finished processing dependencies for gns3-server==1.5.4.dev1

travis_time:end:0400f684:start=1492086409776386038,finish=1492086430394039589,duration=20617653551[0Ktravis_fold:end:install.1[0Ktravis_fold:start:install.2[0Ktravis_time:start:212db9c4[0K$ pip install -rdev-requirements.txt
Requirement already satisfied: jsonschema>=2.4.0 in /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/jsonschema-2.6.0-py3.5.egg (from -r requirements.txt (line 1))
Requirement already satisfied: aiohttp<=1.4.0,>=1.3.5 in /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg (from -r requirements.txt (line 2))
Requirement already satisfied: aiohttp-cors==0.5.1 in /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp_cors-0.5.1-py3.5.egg (from -r requirements.txt (line 3))
Requirement already satisfied: yarl<0.10,>=0.9.8 in /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/yarl-0.9.8-py3.5-linux-x86_64.egg (from -r requirements.txt (line 4))
Requirement already satisfied: typing>=3.5.3.0 in /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/typing-3.6.1-py3.5.egg (from -r requirements.txt (line 5))
Requirement already satisfied: Jinja2>=2.7.3 in /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/Jinja2-2.9.6-py3.5.egg (from -r requirements.txt (line 6))
Requirement already satisfied: raven>=5.23.0 in /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/raven-6.0.0-py3.5.egg (from -r requirements.txt (line 7))
Requirement already satisfied: psutil>=3.0.0 in /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/psutil-5.2.2-py3.5-linux-x86_64.egg (from -r requirements.txt (line 8))
Requirement already satisfied: zipstream>=1.1.4 in /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/zipstream-1.1.4-py3.5.egg (from -r requirements.txt (line 9))
Collecting sphinx==1.2.3 (from -r dev-requirements.txt (line 3))
  Using cached Sphinx-1.2.3-py3-none-any.whl
Collecting pytest==2.8.2 (from -r dev-requirements.txt (line 4))
  Using cached pytest-2.8.2-py2.py3-none-any.whl
Collecting pep8==1.5.7 (from -r dev-requirements.txt (line 5))
  Using cached pep8-1.5.7-py2.py3-none-any.whl
Collecting pytest-capturelog==0.7 (from -r dev-requirements.txt (line 6))
Collecting pytest-cov==2.2.0 (from -r dev-requirements.txt (line 7))
  Using cached pytest_cov-2.2.0-py2.py3-none-any.whl
Collecting pytest-timeout==0.5 (from -r dev-requirements.txt (line 8))
  Using cached pytest_timeout-0.5-py2.py3-none-any.whl
Requirement already satisfied: chardet in /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/chardet-3.0.2-py3.5.egg (from aiohttp<=1.4.0,>=1.3.5->-r requirements.txt (line 2))
Requirement already satisfied: multidict>=2.1.4 in /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/multidict-2.1.4-py3.5-linux-x86_64.egg (from aiohttp<=1.4.0,>=1.3.5->-r requirements.txt (line 2))
Requirement already satisfied: async_timeout>=1.1.0 in /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/async_timeout-1.2.0-py3.5.egg (from aiohttp<=1.4.0,>=1.3.5->-r requirements.txt (line 2))
Requirement already satisfied: MarkupSafe>=0.23 in /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/MarkupSafe-1.0-py3.5-linux-x86_64.egg (from Jinja2>=2.7.3->-r requirements.txt (line 6))
Collecting docutils>=0.10 (from sphinx==1.2.3->-r dev-requirements.txt (line 3))
  Using cached docutils-0.13.1-py3-none-any.whl
Collecting Pygments>=1.2 (from sphinx==1.2.3->-r dev-requirements.txt (line 3))
  Using cached Pygments-2.2.0-py2.py3-none-any.whl
Requirement already satisfied: py>=1.4.29 in /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages (from pytest==2.8.2->-r dev-requirements.txt (line 4))
Collecting coverage>=3.7.1 (from pytest-cov==2.2.0->-r dev-requirements.txt (line 7))
  Using cached coverage-4.3.4-cp35-cp35m-manylinux1_x86_64.whl
Installing collected packages: docutils, Pygments, sphinx, pytest, pep8, pytest-capturelog, coverage, pytest-cov, pytest-timeout
  Found existing installation: pytest 3.0.5
    Uninstalling pytest-3.0.5:
      Successfully uninstalled pytest-3.0.5
Successfully installed Pygments-2.2.0 coverage-4.3.4 docutils-0.13.1 pep8-1.5.7 pytest-2.8.2 pytest-capturelog-0.7 pytest-cov-2.2.0 pytest-timeout-0.5 sphinx-1.2.3

travis_time:end:212db9c4:start=1492086430399735662,finish=1492086434658059670,duration=4258324008[0Ktravis_fold:end:install.2[0Ktravis_fold:start:install.3[0Ktravis_time:start:0310aa84[0K$ pip install coveralls
Collecting coveralls
  Using cached coveralls-1.1-py2.py3-none-any.whl
Collecting requests>=1.0.0 (from coveralls)
  Using cached requests-2.13.0-py2.py3-none-any.whl
Collecting docopt>=0.6.1 (from coveralls)
Requirement already satisfied: coverage>=3.6 in /home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages (from coveralls)
Installing collected packages: requests, docopt, coveralls
Successfully installed coveralls-1.1 docopt-0.6.2 requests-2.13.0

travis_time:end:0310aa84:start=1492086434663838611,finish=1492086436127905575,duration=1464066964[0Ktravis_fold:end:install.3[0Ktravis_time:start:05085e64[0K$ py.test -v -s tests
[1m============================= test session starts ==============================[0m
platform linux -- Python 3.5.2, pytest-2.8.2, py-1.4.32, pluggy-0.3.1 -- /home/travis/virtualenv/python3.5.2/bin/python
cachedir: .cache
rootdir: /home/travis/build/GNS3/gns3-server, inifile: tox.ini
plugins: timeout-0.5, cov-2.2.0, capturelog-0.7
[1mcollecting 0 items[0m[1mcollecting 0 items[0m[1mcollecting 4 items[0m[1mcollecting 7 items[0m[1mcollecting 11 items[0m[1mcollecting 12 items[0m[1mcollecting 14 items[0m[1mcollecting 21 items[0m[1mcollecting 23 items[0m[1mcollecting 35 items[0m[1mcollecting 38 items[0m[1mcollecting 41 items[0m[1mcollecting 64 items[0m[1mcollecting 66 items[0m[1mcollecting 92 items[0m[1mcollecting 117 items[0m[1mcollecting 122 items[0m[1mcollecting 132 items[0m[1mcollecting 144 items[0m[1mcollecting 152 items[0m[1mcollecting 164 items[0m[1mcollecting 173 items[0m[1mcollecting 201 items[0m[1mcollecting 203 items[0m[1mcollecting 207 items[0m[1mcollecting 253 items[0m[1mcollecting 259 items[0m[1mcollecting 261 items[0m[1mcollecting 265 items[0m[1mcollecting 294 items[0m[1mcollecting 299 items[0m[1mcollecting 307 items[0m[1mcollecting 358 items[0m[1mcollecting 363 items[0m[1mcollecting 368 items[0m[1mcollecting 369 items[0m[1mcollecting 373 items[0m[1mcollecting 376 items[0m[1mcollecting 394 items[0m[1mcollecting 399 items[0m[1mcollecting 404 items[0m[1mcollecting 406 items[0m[1mcollecting 407 items[0m[1mcollecting 409 items[0m[1mcollected 409 items 
[0m
tests/test_config.py::test_get_section_config [32mPASSED[0m
tests/test_config.py::test_set_section_config [32mPASSED[0m
tests/test_config.py::test_set [32mPASSED[0m
tests/test_config.py::test_reload [32mPASSED[0m
tests/test_run.py::test_locale_check [32mPASSED[0m
tests/test_run.py::test_parse_arguments [32mPASSED[0m
tests/test_run.py::test_set_config_with_args [32mPASSED[0m
tests/test_utils.py::test_force_unix_path [32mPASSED[0m
tests/test_utils.py::test_macaddress_to_int [32mPASSED[0m
tests/test_utils.py::test_int_to_macaddress [32mPASSED[0m
tests/test_utils.py::test_parse_version [32mPASSED[0m
tests/controller/test_controller.py::test_isEnabled [32mPASSED[0m
tests/handlers/test_index.py::test_index [32mPASSED[0m
tests/handlers/test_index.py::test_status [32mPASSED[0m
tests/handlers/test_upload.py::test_index_upload [32mPASSED[0m
tests/handlers/test_upload.py::test_upload [32mPASSED[0m
tests/handlers/test_upload.py::test_upload_previous_checksum [32mPASSED[0m
tests/handlers/test_upload.py::test_upload_images_backup [32mPASSED[0m
tests/handlers/test_upload.py::test_upload_projects_backup [32mPASSED[0m
tests/handlers/test_upload.py::test_backup_images 2048
[32mPASSED[0m
tests/handlers/test_upload.py::test_backup_projects [32mPASSED[0m
tests/handlers/api/test_config.py::test_reload_accepted [32mPASSED[0m
tests/handlers/api/test_config.py::test_reload_forbidden [32mPASSED[0m
tests/handlers/api/test_docker.py::test_docker_create [32mPASSED[0mCould not close VM Docker has returned an error: [Errno 2] Cannot connect to host docker:80 ssl:False [No such file or directory]
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/connector.py", line 367, in connect
    self._conn_timeout, loop=self._loop)
  File "/opt/python/3.5.2/lib/python3.5/asyncio/tasks.py", line 392, in wait_for
    return fut.result()
  File "/opt/python/3.5.2/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/opt/python/3.5.2/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/connector.py", line 871, in _create_connection
    self._factory, self._path))
  File "/opt/python/3.5.2/lib/python3.5/asyncio/unix_events.py", line 229, in create_unix_connection
    yield from self.sock_connect(sock, path)
  File "/opt/python/3.5.2/lib/python3.5/asyncio/futures.py", line 363, in __iter__
    return self.result()  # May raise too.
  File "/opt/python/3.5.2/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/opt/python/3.5.2/lib/python3.5/asyncio/selector_events.py", line 414, in _sock_connect
    sock.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 115, in http_query
    headers={"content-type": "application/json", },
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/client.py", line 637, in __iter__
    return (yield from self._coro)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/client.py", line 217, in _request
    conn = yield from self._connector.connect(req)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/connector.py", line 380, in connect
    .format(key, exc.strerror)) from exc
aiohttp.errors.ClientOSError: [Errno 2] Cannot connect to host docker:80 ssl:False [No such file or directory]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/base_manager.py", line 120, in unload
    future.result()
  File "/opt/python/3.5.2/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/opt/python/3.5.2/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/base_manager.py", line 254, in close_vm
    yield from vm.close()
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/docker_vm.py", line 579, in close
    yield from self.reset()
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/docker_vm.py", line 584, in reset
    state = yield from self._get_container_state()
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/docker_vm.py", line 180, in _get_container_state
    result = yield from self.manager.query("GET", "containers/{}/json".format(self._cid))
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 85, in query
    response = yield from self.http_query(method, path, data=data, params=params)
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 112, in http_query
    connector=(yield from self.connector()),
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 59, in connector
    version = yield from self.query("GET", "version")
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 85, in query
    response = yield from self.http_query(method, path, data=data, params=params)
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 118, in http_query
    raise DockerError("Docker has returned an error: {}".format(str(e)))
gns3server.modules.docker.docker_error.DockerError: Docker has returned an error: [Errno 2] Cannot connect to host docker:80 ssl:False [No such file or directory]

tests/handlers/api/test_docker.py::test_docker_start [32mPASSED[0mCould not close VM Docker has returned an error: [Errno 2] Cannot connect to host docker:80 ssl:False [No such file or directory]
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/connector.py", line 367, in connect
    self._conn_timeout, loop=self._loop)
  File "/opt/python/3.5.2/lib/python3.5/asyncio/tasks.py", line 392, in wait_for
    return fut.result()
  File "/opt/python/3.5.2/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/opt/python/3.5.2/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/connector.py", line 871, in _create_connection
    self._factory, self._path))
  File "/opt/python/3.5.2/lib/python3.5/asyncio/unix_events.py", line 229, in create_unix_connection
    yield from self.sock_connect(sock, path)
  File "/opt/python/3.5.2/lib/python3.5/asyncio/futures.py", line 363, in __iter__
    return self.result()  # May raise too.
  File "/opt/python/3.5.2/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/opt/python/3.5.2/lib/python3.5/asyncio/selector_events.py", line 414, in _sock_connect
    sock.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 115, in http_query
    headers={"content-type": "application/json", },
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/client.py", line 637, in __iter__
    return (yield from self._coro)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/client.py", line 217, in _request
    conn = yield from self._connector.connect(req)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/connector.py", line 380, in connect
    .format(key, exc.strerror)) from exc
aiohttp.errors.ClientOSError: [Errno 2] Cannot connect to host docker:80 ssl:False [No such file or directory]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/base_manager.py", line 120, in unload
    future.result()
  File "/opt/python/3.5.2/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/opt/python/3.5.2/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/base_manager.py", line 254, in close_vm
    yield from vm.close()
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/docker_vm.py", line 579, in close
    yield from self.reset()
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/docker_vm.py", line 584, in reset
    state = yield from self._get_container_state()
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/docker_vm.py", line 180, in _get_container_state
    result = yield from self.manager.query("GET", "containers/{}/json".format(self._cid))
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 85, in query
    response = yield from self.http_query(method, path, data=data, params=params)
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 112, in http_query
    connector=(yield from self.connector()),
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 59, in connector
    version = yield from self.query("GET", "version")
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 85, in query
    response = yield from self.http_query(method, path, data=data, params=params)
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 118, in http_query
    raise DockerError("Docker has returned an error: {}".format(str(e)))
gns3server.modules.docker.docker_error.DockerError: Docker has returned an error: [Errno 2] Cannot connect to host docker:80 ssl:False [No such file or directory]

tests/handlers/api/test_docker.py::test_docker_stop [32mPASSED[0mCould not close VM Docker has returned an error: [Errno 2] Cannot connect to host docker:80 ssl:False [No such file or directory]
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/connector.py", line 367, in connect
    self._conn_timeout, loop=self._loop)
  File "/opt/python/3.5.2/lib/python3.5/asyncio/tasks.py", line 392, in wait_for
    return fut.result()
  File "/opt/python/3.5.2/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/opt/python/3.5.2/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/connector.py", line 871, in _create_connection
    self._factory, self._path))
  File "/opt/python/3.5.2/lib/python3.5/asyncio/unix_events.py", line 229, in create_unix_connection
    yield from self.sock_connect(sock, path)
  File "/opt/python/3.5.2/lib/python3.5/asyncio/futures.py", line 363, in __iter__
    return self.result()  # May raise too.
  File "/opt/python/3.5.2/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/opt/python/3.5.2/lib/python3.5/asyncio/selector_events.py", line 414, in _sock_connect
    sock.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 115, in http_query
    headers={"content-type": "application/json", },
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/client.py", line 637, in __iter__
    return (yield from self._coro)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/client.py", line 217, in _request
    conn = yield from self._connector.connect(req)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/connector.py", line 380, in connect
    .format(key, exc.strerror)) from exc
aiohttp.errors.ClientOSError: [Errno 2] Cannot connect to host docker:80 ssl:False [No such file or directory]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/base_manager.py", line 120, in unload
    future.result()
  File "/opt/python/3.5.2/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/opt/python/3.5.2/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/base_manager.py", line 254, in close_vm
    yield from vm.close()
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/docker_vm.py", line 579, in close
    yield from self.reset()
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/docker_vm.py", line 584, in reset
    state = yield from self._get_container_state()
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/docker_vm.py", line 180, in _get_container_state
    result = yield from self.manager.query("GET", "containers/{}/json".format(self._cid))
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 85, in query
    response = yield from self.http_query(method, path, data=data, params=params)
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 112, in http_query
    connector=(yield from self.connector()),
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 59, in connector
    version = yield from self.query("GET", "version")
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 85, in query
    response = yield from self.http_query(method, path, data=data, params=params)
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 118, in http_query
    raise DockerError("Docker has returned an error: {}".format(str(e)))
gns3server.modules.docker.docker_error.DockerError: Docker has returned an error: [Errno 2] Cannot connect to host docker:80 ssl:False [No such file or directory]

tests/handlers/api/test_docker.py::test_docker_delete [32mPASSED[0mCould not close VM Docker has returned an error: [Errno 2] Cannot connect to host docker:80 ssl:False [No such file or directory]
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/connector.py", line 367, in connect
    self._conn_timeout, loop=self._loop)
  File "/opt/python/3.5.2/lib/python3.5/asyncio/tasks.py", line 392, in wait_for
    return fut.result()
  File "/opt/python/3.5.2/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/opt/python/3.5.2/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/connector.py", line 871, in _create_connection
    self._factory, self._path))
  File "/opt/python/3.5.2/lib/python3.5/asyncio/unix_events.py", line 229, in create_unix_connection
    yield from self.sock_connect(sock, path)
  File "/opt/python/3.5.2/lib/python3.5/asyncio/futures.py", line 363, in __iter__
    return self.result()  # May raise too.
  File "/opt/python/3.5.2/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/opt/python/3.5.2/lib/python3.5/asyncio/selector_events.py", line 414, in _sock_connect
    sock.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 115, in http_query
    headers={"content-type": "application/json", },
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/client.py", line 637, in __iter__
    return (yield from self._coro)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/client.py", line 217, in _request
    conn = yield from self._connector.connect(req)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/connector.py", line 380, in connect
    .format(key, exc.strerror)) from exc
aiohttp.errors.ClientOSError: [Errno 2] Cannot connect to host docker:80 ssl:False [No such file or directory]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/base_manager.py", line 120, in unload
    future.result()
  File "/opt/python/3.5.2/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/opt/python/3.5.2/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/base_manager.py", line 254, in close_vm
    yield from vm.close()
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/docker_vm.py", line 579, in close
    yield from self.reset()
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/docker_vm.py", line 584, in reset
    state = yield from self._get_container_state()
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/docker_vm.py", line 180, in _get_container_state
    result = yield from self.manager.query("GET", "containers/{}/json".format(self._cid))
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 85, in query
    response = yield from self.http_query(method, path, data=data, params=params)
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 112, in http_query
    connector=(yield from self.connector()),
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 59, in connector
    version = yield from self.query("GET", "version")
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 85, in query
    response = yield from self.http_query(method, path, data=data, params=params)
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 118, in http_query
    raise DockerError("Docker has returned an error: {}".format(str(e)))
gns3server.modules.docker.docker_error.DockerError: Docker has returned an error: [Errno 2] Cannot connect to host docker:80 ssl:False [No such file or directory]

tests/handlers/api/test_docker.py::test_docker_reload [32mPASSED[0mCould not close VM Docker has returned an error: [Errno 2] Cannot connect to host docker:80 ssl:False [No such file or directory]
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/connector.py", line 367, in connect
    self._conn_timeout, loop=self._loop)
  File "/opt/python/3.5.2/lib/python3.5/asyncio/tasks.py", line 392, in wait_for
    return fut.result()
  File "/opt/python/3.5.2/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/opt/python/3.5.2/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/connector.py", line 871, in _create_connection
    self._factory, self._path))
  File "/opt/python/3.5.2/lib/python3.5/asyncio/unix_events.py", line 229, in create_unix_connection
    yield from self.sock_connect(sock, path)
  File "/opt/python/3.5.2/lib/python3.5/asyncio/futures.py", line 363, in __iter__
    return self.result()  # May raise too.
  File "/opt/python/3.5.2/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/opt/python/3.5.2/lib/python3.5/asyncio/selector_events.py", line 414, in _sock_connect
    sock.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 115, in http_query
    headers={"content-type": "application/json", },
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/client.py", line 637, in __iter__
    return (yield from self._coro)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/client.py", line 217, in _request
    conn = yield from self._connector.connect(req)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/connector.py", line 380, in connect
    .format(key, exc.strerror)) from exc
aiohttp.errors.ClientOSError: [Errno 2] Cannot connect to host docker:80 ssl:False [No such file or directory]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/base_manager.py", line 120, in unload
    future.result()
  File "/opt/python/3.5.2/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/opt/python/3.5.2/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/base_manager.py", line 254, in close_vm
    yield from vm.close()
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/docker_vm.py", line 579, in close
    yield from self.reset()
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/docker_vm.py", line 584, in reset
    state = yield from self._get_container_state()
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/docker_vm.py", line 180, in _get_container_state
    result = yield from self.manager.query("GET", "containers/{}/json".format(self._cid))
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 85, in query
    response = yield from self.http_query(method, path, data=data, params=params)
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 112, in http_query
    connector=(yield from self.connector()),
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 59, in connector
    version = yield from self.query("GET", "version")
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 85, in query
    response = yield from self.http_query(method, path, data=data, params=params)
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 118, in http_query
    raise DockerError("Docker has returned an error: {}".format(str(e)))
gns3server.modules.docker.docker_error.DockerError: Docker has returned an error: [Errno 2] Cannot connect to host docker:80 ssl:False [No such file or directory]

tests/handlers/api/test_docker.py::test_docker_nio_create_udp [32mPASSED[0mCould not close VM Docker has returned an error: [Errno 2] Cannot connect to host docker:80 ssl:False [No such file or directory]
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/connector.py", line 367, in connect
    self._conn_timeout, loop=self._loop)
  File "/opt/python/3.5.2/lib/python3.5/asyncio/tasks.py", line 392, in wait_for
    return fut.result()
  File "/opt/python/3.5.2/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/opt/python/3.5.2/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/connector.py", line 871, in _create_connection
    self._factory, self._path))
  File "/opt/python/3.5.2/lib/python3.5/asyncio/unix_events.py", line 229, in create_unix_connection
    yield from self.sock_connect(sock, path)
  File "/opt/python/3.5.2/lib/python3.5/asyncio/futures.py", line 363, in __iter__
    return self.result()  # May raise too.
  File "/opt/python/3.5.2/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/opt/python/3.5.2/lib/python3.5/asyncio/selector_events.py", line 414, in _sock_connect
    sock.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 115, in http_query
    headers={"content-type": "application/json", },
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/client.py", line 637, in __iter__
    return (yield from self._coro)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/client.py", line 217, in _request
    conn = yield from self._connector.connect(req)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/connector.py", line 380, in connect
    .format(key, exc.strerror)) from exc
aiohttp.errors.ClientOSError: [Errno 2] Cannot connect to host docker:80 ssl:False [No such file or directory]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/base_manager.py", line 120, in unload
    future.result()
  File "/opt/python/3.5.2/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/opt/python/3.5.2/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/base_manager.py", line 254, in close_vm
    yield from vm.close()
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/docker_vm.py", line 579, in close
    yield from self.reset()
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/docker_vm.py", line 584, in reset
    state = yield from self._get_container_state()
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/docker_vm.py", line 180, in _get_container_state
    result = yield from self.manager.query("GET", "containers/{}/json".format(self._cid))
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 85, in query
    response = yield from self.http_query(method, path, data=data, params=params)
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 112, in http_query
    connector=(yield from self.connector()),
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 59, in connector
    version = yield from self.query("GET", "version")
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 85, in query
    response = yield from self.http_query(method, path, data=data, params=params)
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 118, in http_query
    raise DockerError("Docker has returned an error: {}".format(str(e)))
gns3server.modules.docker.docker_error.DockerError: Docker has returned an error: [Errno 2] Cannot connect to host docker:80 ssl:False [No such file or directory]

tests/handlers/api/test_docker.py::test_docker_delete_nio [32mPASSED[0mCould not close VM Docker has returned an error: [Errno 2] Cannot connect to host docker:80 ssl:False [No such file or directory]
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/connector.py", line 367, in connect
    self._conn_timeout, loop=self._loop)
  File "/opt/python/3.5.2/lib/python3.5/asyncio/tasks.py", line 392, in wait_for
    return fut.result()
  File "/opt/python/3.5.2/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/opt/python/3.5.2/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/connector.py", line 871, in _create_connection
    self._factory, self._path))
  File "/opt/python/3.5.2/lib/python3.5/asyncio/unix_events.py", line 229, in create_unix_connection
    yield from self.sock_connect(sock, path)
  File "/opt/python/3.5.2/lib/python3.5/asyncio/futures.py", line 363, in __iter__
    return self.result()  # May raise too.
  File "/opt/python/3.5.2/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/opt/python/3.5.2/lib/python3.5/asyncio/selector_events.py", line 414, in _sock_connect
    sock.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 115, in http_query
    headers={"content-type": "application/json", },
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/client.py", line 637, in __iter__
    return (yield from self._coro)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/client.py", line 217, in _request
    conn = yield from self._connector.connect(req)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/connector.py", line 380, in connect
    .format(key, exc.strerror)) from exc
aiohttp.errors.ClientOSError: [Errno 2] Cannot connect to host docker:80 ssl:False [No such file or directory]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/base_manager.py", line 120, in unload
    future.result()
  File "/opt/python/3.5.2/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/opt/python/3.5.2/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/base_manager.py", line 254, in close_vm
    yield from vm.close()
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/docker_vm.py", line 579, in close
    yield from self.reset()
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/docker_vm.py", line 584, in reset
    state = yield from self._get_container_state()
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/docker_vm.py", line 180, in _get_container_state
    result = yield from self.manager.query("GET", "containers/{}/json".format(self._cid))
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 85, in query
    response = yield from self.http_query(method, path, data=data, params=params)
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 112, in http_query
    connector=(yield from self.connector()),
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 59, in connector
    version = yield from self.query("GET", "version")
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 85, in query
    response = yield from self.http_query(method, path, data=data, params=params)
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 118, in http_query
    raise DockerError("Docker has returned an error: {}".format(str(e)))
gns3server.modules.docker.docker_error.DockerError: Docker has returned an error: [Errno 2] Cannot connect to host docker:80 ssl:False [No such file or directory]

tests/handlers/api/test_docker.py::test_docker_update [32mPASSED[0mCould not close VM Docker has returned an error: [Errno 2] Cannot connect to host docker:80 ssl:False [No such file or directory]
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/connector.py", line 367, in connect
    self._conn_timeout, loop=self._loop)
  File "/opt/python/3.5.2/lib/python3.5/asyncio/tasks.py", line 392, in wait_for
    return fut.result()
  File "/opt/python/3.5.2/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/opt/python/3.5.2/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/connector.py", line 871, in _create_connection
    self._factory, self._path))
  File "/opt/python/3.5.2/lib/python3.5/asyncio/unix_events.py", line 229, in create_unix_connection
    yield from self.sock_connect(sock, path)
  File "/opt/python/3.5.2/lib/python3.5/asyncio/futures.py", line 363, in __iter__
    return self.result()  # May raise too.
  File "/opt/python/3.5.2/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/opt/python/3.5.2/lib/python3.5/asyncio/selector_events.py", line 414, in _sock_connect
    sock.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 115, in http_query
    headers={"content-type": "application/json", },
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/client.py", line 637, in __iter__
    return (yield from self._coro)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/client.py", line 217, in _request
    conn = yield from self._connector.connect(req)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/connector.py", line 380, in connect
    .format(key, exc.strerror)) from exc
aiohttp.errors.ClientOSError: [Errno 2] Cannot connect to host docker:80 ssl:False [No such file or directory]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/base_manager.py", line 120, in unload
    future.result()
  File "/opt/python/3.5.2/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/opt/python/3.5.2/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/base_manager.py", line 254, in close_vm
    yield from vm.close()
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/docker_vm.py", line 579, in close
    yield from self.reset()
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/docker_vm.py", line 584, in reset
    state = yield from self._get_container_state()
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/docker_vm.py", line 180, in _get_container_state
    result = yield from self.manager.query("GET", "containers/{}/json".format(self._cid))
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 85, in query
    response = yield from self.http_query(method, path, data=data, params=params)
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 112, in http_query
    connector=(yield from self.connector()),
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 59, in connector
    version = yield from self.query("GET", "version")
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 85, in query
    response = yield from self.http_query(method, path, data=data, params=params)
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 118, in http_query
    raise DockerError("Docker has returned an error: {}".format(str(e)))
gns3server.modules.docker.docker_error.DockerError: Docker has returned an error: [Errno 2] Cannot connect to host docker:80 ssl:False [No such file or directory]

tests/handlers/api/test_docker.py::test_docker_start_capture [32mPASSED[0mCould not close VM Docker has returned an error: [Errno 2] Cannot connect to host docker:80 ssl:False [No such file or directory]
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/connector.py", line 367, in connect
    self._conn_timeout, loop=self._loop)
  File "/opt/python/3.5.2/lib/python3.5/asyncio/tasks.py", line 392, in wait_for
    return fut.result()
  File "/opt/python/3.5.2/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/opt/python/3.5.2/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/connector.py", line 871, in _create_connection
    self._factory, self._path))
  File "/opt/python/3.5.2/lib/python3.5/asyncio/unix_events.py", line 229, in create_unix_connection
    yield from self.sock_connect(sock, path)
  File "/opt/python/3.5.2/lib/python3.5/asyncio/futures.py", line 363, in __iter__
    return self.result()  # May raise too.
  File "/opt/python/3.5.2/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/opt/python/3.5.2/lib/python3.5/asyncio/selector_events.py", line 414, in _sock_connect
    sock.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 115, in http_query
    headers={"content-type": "application/json", },
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/client.py", line 637, in __iter__
    return (yield from self._coro)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/client.py", line 217, in _request
    conn = yield from self._connector.connect(req)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/connector.py", line 380, in connect
    .format(key, exc.strerror)) from exc
aiohttp.errors.ClientOSError: [Errno 2] Cannot connect to host docker:80 ssl:False [No such file or directory]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/base_manager.py", line 120, in unload
    future.result()
  File "/opt/python/3.5.2/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/opt/python/3.5.2/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/base_manager.py", line 254, in close_vm
    yield from vm.close()
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/docker_vm.py", line 579, in close
    yield from self.reset()
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/docker_vm.py", line 584, in reset
    state = yield from self._get_container_state()
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/docker_vm.py", line 180, in _get_container_state
    result = yield from self.manager.query("GET", "containers/{}/json".format(self._cid))
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 85, in query
    response = yield from self.http_query(method, path, data=data, params=params)
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 112, in http_query
    connector=(yield from self.connector()),
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 59, in connector
    version = yield from self.query("GET", "version")
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 85, in query
    response = yield from self.http_query(method, path, data=data, params=params)
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 118, in http_query
    raise DockerError("Docker has returned an error: {}".format(str(e)))
gns3server.modules.docker.docker_error.DockerError: Docker has returned an error: [Errno 2] Cannot connect to host docker:80 ssl:False [No such file or directory]

tests/handlers/api/test_docker.py::test_docker_start_capture_not_started [32mPASSED[0mCould not close VM Docker has returned an error: [Errno 2] Cannot connect to host docker:80 ssl:False [No such file or directory]
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/connector.py", line 367, in connect
    self._conn_timeout, loop=self._loop)
  File "/opt/python/3.5.2/lib/python3.5/asyncio/tasks.py", line 392, in wait_for
    return fut.result()
  File "/opt/python/3.5.2/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/opt/python/3.5.2/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/connector.py", line 871, in _create_connection
    self._factory, self._path))
  File "/opt/python/3.5.2/lib/python3.5/asyncio/unix_events.py", line 229, in create_unix_connection
    yield from self.sock_connect(sock, path)
  File "/opt/python/3.5.2/lib/python3.5/asyncio/futures.py", line 363, in __iter__
    return self.result()  # May raise too.
  File "/opt/python/3.5.2/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/opt/python/3.5.2/lib/python3.5/asyncio/selector_events.py", line 414, in _sock_connect
    sock.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 115, in http_query
    headers={"content-type": "application/json", },
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/client.py", line 637, in __iter__
    return (yield from self._coro)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/client.py", line 217, in _request
    conn = yield from self._connector.connect(req)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/connector.py", line 380, in connect
    .format(key, exc.strerror)) from exc
aiohttp.errors.ClientOSError: [Errno 2] Cannot connect to host docker:80 ssl:False [No such file or directory]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/base_manager.py", line 120, in unload
    future.result()
  File "/opt/python/3.5.2/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/opt/python/3.5.2/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/base_manager.py", line 254, in close_vm
    yield from vm.close()
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/docker_vm.py", line 579, in close
    yield from self.reset()
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/docker_vm.py", line 584, in reset
    state = yield from self._get_container_state()
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/docker_vm.py", line 180, in _get_container_state
    result = yield from self.manager.query("GET", "containers/{}/json".format(self._cid))
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 85, in query
    response = yield from self.http_query(method, path, data=data, params=params)
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 112, in http_query
    connector=(yield from self.connector()),
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 59, in connector
    version = yield from self.query("GET", "version")
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 85, in query
    response = yield from self.http_query(method, path, data=data, params=params)
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 118, in http_query
    raise DockerError("Docker has returned an error: {}".format(str(e)))
gns3server.modules.docker.docker_error.DockerError: Docker has returned an error: [Errno 2] Cannot connect to host docker:80 ssl:False [No such file or directory]

tests/handlers/api/test_docker.py::test_docker_stop_capture [32mPASSED[0mCould not close VM Docker has returned an error: [Errno 2] Cannot connect to host docker:80 ssl:False [No such file or directory]
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/connector.py", line 367, in connect
    self._conn_timeout, loop=self._loop)
  File "/opt/python/3.5.2/lib/python3.5/asyncio/tasks.py", line 392, in wait_for
    return fut.result()
  File "/opt/python/3.5.2/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/opt/python/3.5.2/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/connector.py", line 871, in _create_connection
    self._factory, self._path))
  File "/opt/python/3.5.2/lib/python3.5/asyncio/unix_events.py", line 229, in create_unix_connection
    yield from self.sock_connect(sock, path)
  File "/opt/python/3.5.2/lib/python3.5/asyncio/futures.py", line 363, in __iter__
    return self.result()  # May raise too.
  File "/opt/python/3.5.2/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/opt/python/3.5.2/lib/python3.5/asyncio/selector_events.py", line 414, in _sock_connect
    sock.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 115, in http_query
    headers={"content-type": "application/json", },
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/client.py", line 637, in __iter__
    return (yield from self._coro)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/client.py", line 217, in _request
    conn = yield from self._connector.connect(req)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/connector.py", line 380, in connect
    .format(key, exc.strerror)) from exc
aiohttp.errors.ClientOSError: [Errno 2] Cannot connect to host docker:80 ssl:False [No such file or directory]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/base_manager.py", line 120, in unload
    future.result()
  File "/opt/python/3.5.2/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/opt/python/3.5.2/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/base_manager.py", line 254, in close_vm
    yield from vm.close()
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/docker_vm.py", line 579, in close
    yield from self.reset()
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/docker_vm.py", line 584, in reset
    state = yield from self._get_container_state()
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/docker_vm.py", line 180, in _get_container_state
    result = yield from self.manager.query("GET", "containers/{}/json".format(self._cid))
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 85, in query
    response = yield from self.http_query(method, path, data=data, params=params)
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 112, in http_query
    connector=(yield from self.connector()),
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 59, in connector
    version = yield from self.query("GET", "version")
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 85, in query
    response = yield from self.http_query(method, path, data=data, params=params)
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 118, in http_query
    raise DockerError("Docker has returned an error: {}".format(str(e)))
gns3server.modules.docker.docker_error.DockerError: Docker has returned an error: [Errno 2] Cannot connect to host docker:80 ssl:False [No such file or directory]

tests/handlers/api/test_docker.py::test_docker_stop_capture_not_started [32mPASSED[0mCould not close VM Docker has returned an error: [Errno 2] Cannot connect to host docker:80 ssl:False [No such file or directory]
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/connector.py", line 367, in connect
    self._conn_timeout, loop=self._loop)
  File "/opt/python/3.5.2/lib/python3.5/asyncio/tasks.py", line 392, in wait_for
    return fut.result()
  File "/opt/python/3.5.2/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/opt/python/3.5.2/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/connector.py", line 871, in _create_connection
    self._factory, self._path))
  File "/opt/python/3.5.2/lib/python3.5/asyncio/unix_events.py", line 229, in create_unix_connection
    yield from self.sock_connect(sock, path)
  File "/opt/python/3.5.2/lib/python3.5/asyncio/futures.py", line 363, in __iter__
    return self.result()  # May raise too.
  File "/opt/python/3.5.2/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/opt/python/3.5.2/lib/python3.5/asyncio/selector_events.py", line 414, in _sock_connect
    sock.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 115, in http_query
    headers={"content-type": "application/json", },
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/client.py", line 637, in __iter__
    return (yield from self._coro)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/client.py", line 217, in _request
    conn = yield from self._connector.connect(req)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/aiohttp-1.3.5-py3.5-linux-x86_64.egg/aiohttp/connector.py", line 380, in connect
    .format(key, exc.strerror)) from exc
aiohttp.errors.ClientOSError: [Errno 2] Cannot connect to host docker:80 ssl:False [No such file or directory]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/base_manager.py", line 120, in unload
    future.result()
  File "/opt/python/3.5.2/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/opt/python/3.5.2/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/base_manager.py", line 254, in close_vm
    yield from vm.close()
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/docker_vm.py", line 579, in close
    yield from self.reset()
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/docker_vm.py", line 584, in reset
    state = yield from self._get_container_state()
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/docker_vm.py", line 180, in _get_container_state
    result = yield from self.manager.query("GET", "containers/{}/json".format(self._cid))
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 85, in query
    response = yield from self.http_query(method, path, data=data, params=params)
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 112, in http_query
    connector=(yield from self.connector()),
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 59, in connector
    version = yield from self.query("GET", "version")
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 85, in query
    response = yield from self.http_query(method, path, data=data, params=params)
  File "/home/travis/build/GNS3/gns3-server/gns3server/modules/docker/__init__.py", line 118, in http_query
    raise DockerError("Docker has returned an error: {}".format(str(e)))
gns3server.modules.docker.docker_error.DockerError: Docker has returned an error: [Errno 2] Cannot connect to host docker:80 ssl:False [No such file or directory]

tests/handlers/api/test_dynamips.py::test_vms [32mPASSED[0m
tests/handlers/api/test_dynamips.py::test_upload_vm [32mPASSED[0m
tests/handlers/api/test_dynamips.py::test_upload_vm_permission_denied [32mPASSED[0m
tests/handlers/api/test_file.py::test_stream [32mPASSED[0mRequest canceled

tests/handlers/api/test_file.py::test_stream_file_not_pcap [32mPASSED[0m
tests/handlers/api/test_file.py::test_stream_file_not_found [32mPASSED[0m
tests/handlers/api/test_iou.py::test_iou_create [32mPASSED[0m
tests/handlers/api/test_iou.py::test_iou_create_with_params [32mPASSED[0m
tests/handlers/api/test_iou.py::test_iou_create_startup_config_already_exist [32mPASSED[0m
tests/handlers/api/test_iou.py::test_iou_get [32mPASSED[0m
tests/handlers/api/test_iou.py::test_iou_start [32mPASSED[0m
tests/handlers/api/test_iou.py::test_iou_start_with_iourc iourc_content
/tmp/tmp4002jfhs/iourc
[32mPASSED[0m
tests/handlers/api/test_iou.py::test_iou_stop [32mPASSED[0m
tests/handlers/api/test_iou.py::test_iou_reload [32mPASSED[0m
tests/handlers/api/test_iou.py::test_iou_delete [32mPASSED[0m
tests/handlers/api/test_iou.py::test_iou_update [32mPASSED[0m
tests/handlers/api/test_iou.py::test_iou_nio_create_udp [32mPASSED[0m
tests/handlers/api/test_iou.py::test_iou_nio_create_ethernet [32mPASSED[0m
tests/handlers/api/test_iou.py::test_iou_nio_create_ethernet_different_port [32mPASSED[0m
tests/handlers/api/test_iou.py::test_iou_nio_create_tap [32mPASSED[0m
tests/handlers/api/test_iou.py::test_iou_delete_nio [32mPASSED[0m
tests/handlers/api/test_iou.py::test_iou_start_capture [32mPASSED[0m
tests/handlers/api/test_iou.py::test_iou_start_capture_not_started [32mPASSED[0m
tests/handlers/api/test_iou.py::test_iou_stop_capture [32mPASSED[0m
tests/handlers/api/test_iou.py::test_iou_stop_capture_not_started [32mPASSED[0m
tests/handlers/api/test_iou.py::test_get_configs_without_configs_file [32mPASSED[0m
tests/handlers/api/test_iou.py::test_get_configs_with_startup_config_file [32mPASSED[0m
tests/handlers/api/test_iou.py::test_vms [32mPASSED[0m
tests/handlers/api/test_iou.py::test_upload_vm [32mPASSED[0m
tests/handlers/api/test_network.py::test_udp_allocation [32mPASSED[0m
tests/handlers/api/test_network.py::test_interfaces [33mSKIPPED[0m
tests/handlers/api/test_project.py::test_create_project_with_path [32mPASSED[0m
tests/handlers/api/test_project.py::test_create_project_without_dir [32mPASSED[0m
tests/handlers/api/test_project.py::test_create_temporary_project [32mPASSED[0m
tests/handlers/api/test_project.py::test_create_project_with_uuid [32mPASSED[0m
tests/handlers/api/test_project.py::test_show_project [32mPASSED[0m
tests/handlers/api/test_project.py::test_show_project_invalid_uuid [32mPASSED[0m
tests/handlers/api/test_project.py::test_list_projects [{'path': '/tmp/tmpwl54bnyp/projects/00010203-0405-0607-0809-0a0b0c0d0e0f', 'project_id': '00010203-0405-0607-0809-0a0b0c0d0e0f', 'name': 'test', 'temporary': False, 'location': '/tmp/tmpwl54bnyp/projects'}, {'path': '/tmp/tmpwl54bnyp/projects/00010203-0405-0607-0809-0a0b0c0d0e0b', 'project_id': '00010203-0405-0607-0809-0a0b0c0d0e0b', 'name': 'test', 'temporary': False, 'location': '/tmp/tmpwl54bnyp/projects'}]
[32mPASSED[0m
tests/handlers/api/test_project.py::test_update_temporary_project [32mPASSED[0m
tests/handlers/api/test_project.py::test_update_path_project_temporary [32mPASSED[0m
tests/handlers/api/test_project.py::test_update_path_project_non_temporary [32mPASSED[0m
tests/handlers/api/test_project.py::test_update_path_project_non_local [32mPASSED[0m
tests/handlers/api/test_project.py::test_commit_project [32mPASSED[0m
tests/handlers/api/test_project.py::test_commit_project_invalid_uuid [32mPASSED[0m
tests/handlers/api/test_project.py::test_delete_project [32mPASSED[0m
tests/handlers/api/test_project.py::test_delete_project_invalid_uuid [32mPASSED[0m
tests/handlers/api/test_project.py::test_close_project [32mPASSED[0m
tests/handlers/api/test_project.py::test_close_project_two_client_connected [32mPASSED[0m
tests/handlers/api/test_project.py::test_close_project_invalid_uuid [32mPASSED[0m
tests/handlers/api/test_project.py::test_notification [32mPASSED[0m
tests/handlers/api/test_project.py::test_notification_invalid_id [32mPASSED[0m
tests/handlers/api/test_project.py::test_list_files [32mPASSED[0m
tests/handlers/api/test_project.py::test_get_file [32mPASSED[0m
tests/handlers/api/test_project.py::test_write_file [32mPASSED[0m
tests/handlers/api/test_project.py::test_export [32mPASSED[0m
tests/handlers/api/test_project.py::test_export_include_image [32mPASSED[0m
tests/handlers/api/test_project.py::test_import [32mPASSED[0m
tests/handlers/api/test_qemu.py::test_qemu_create [32mPASSED[0m
tests/handlers/api/test_qemu.py::test_qemu_create_platform [32mPASSED[0m
tests/handlers/api/test_qemu.py::test_qemu_create_with_params [32mPASSED[0m
tests/handlers/api/test_qemu.py::test_qemu_get [32mPASSED[0m
tests/handlers/api/test_qemu.py::test_qemu_start [32mPASSED[0m
tests/handlers/api/test_qemu.py::test_qemu_stop [32mPASSED[0m
tests/handlers/api/test_qemu.py::test_qemu_reload [32mPASSED[0m
tests/handlers/api/test_qemu.py::test_qemu_suspend [32mPASSED[0m
tests/handlers/api/test_qemu.py::test_qemu_resume [32mPASSED[0m
tests/handlers/api/test_qemu.py::test_qemu_delete [32mPASSED[0m
tests/handlers/api/test_qemu.py::test_qemu_update [32mPASSED[0m
tests/handlers/api/test_qemu.py::test_qemu_nio_create_udp [32mPASSED[0m
tests/handlers/api/test_qemu.py::test_qemu_nio_create_ethernet [32mPASSED[0m
tests/handlers/api/test_qemu.py::test_qemu_delete_nio [32mPASSED[0m
tests/handlers/api/test_qemu.py::test_qemu_list_binaries [32mPASSED[0m
tests/handlers/api/test_qemu.py::test_qemu_list_binaries_filter [32mPASSED[0m
tests/handlers/api/test_qemu.py::test_vms [32mPASSED[0m
tests/handlers/api/test_qemu.py::test_upload_vm [32mPASSED[0m
tests/handlers/api/test_qemu.py::test_upload_vm_ova [32mPASSED[0m
tests/handlers/api/test_qemu.py::test_upload_vm_forbiden_location [32mPASSED[0m
tests/handlers/api/test_qemu.py::test_upload_vm_permission_denied [32mPASSED[0m
tests/handlers/api/test_qemu.py::test_create_img_relative [32mPASSED[0m
tests/handlers/api/test_qemu.py::test_create_img_absolute_non_local [32mPASSED[0m
tests/handlers/api/test_qemu.py::test_create_img_absolute_local [32mPASSED[0m
tests/handlers/api/test_qemu.py::test_capabilities [32mPASSED[0m
tests/handlers/api/test_version.py::test_version_output [32mPASSED[0m
tests/handlers/api/test_version.py::test_version_input [32mPASSED[0m
tests/handlers/api/test_version.py::test_version_invalid_input [32mPASSED[0m
tests/handlers/api/test_version.py::test_version_invalid_input_schema [32mPASSED[0m
tests/handlers/api/test_version.py::test_version_invalid_json [32mPASSED[0m
tests/handlers/api/test_virtualbox.py::test_vbox_create [32mPASSED[0m
tests/handlers/api/test_virtualbox.py::test_vbox_get [32mPASSED[0m
tests/handlers/api/test_virtualbox.py::test_vbox_start [32mPASSED[0m
tests/handlers/api/test_virtualbox.py::test_vbox_stop [32mPASSED[0m
tests/handlers/api/test_virtualbox.py::test_vbox_suspend [32mPASSED[0m
tests/handlers/api/test_virtualbox.py::test_vbox_resume [32mPASSED[0m
tests/handlers/api/test_virtualbox.py::test_vbox_reload [32mPASSED[0m
tests/handlers/api/test_virtualbox.py::test_vbox_nio_create_udp [32mPASSED[0m
tests/handlers/api/test_virtualbox.py::test_vbox_delete_nio [32mPASSED[0m
tests/handlers/api/test_virtualbox.py::test_vbox_update [32mPASSED[0m
tests/handlers/api/test_vpcs.py::test_vpcs_create [32mPASSED[0m
tests/handlers/api/test_vpcs.py::test_vpcs_get [32mPASSED[0m
tests/handlers/api/test_vpcs.py::test_vpcs_create_startup_script [32mPASSED[0m
tests/handlers/api/test_vpcs.py::test_vpcs_create_port [32mPASSED[0m
tests/handlers/api/test_vpcs.py::test_vpcs_nio_create_udp [32mPASSED[0m
tests/handlers/api/test_vpcs.py::test_vpcs_nio_create_tap [32mPASSED[0m
tests/handlers/api/test_vpcs.py::test_vpcs_delete_nio [32mPASSED[0m
tests/handlers/api/test_vpcs.py::test_vpcs_start [32mPASSED[0m
tests/handlers/api/test_vpcs.py::test_vpcs_stop [32mPASSED[0m
tests/handlers/api/test_vpcs.py::test_vpcs_reload [32mPASSED[0m
tests/handlers/api/test_vpcs.py::test_vpcs_delete [32mPASSED[0m
tests/handlers/api/test_vpcs.py::test_vpcs_update [32mPASSED[0m
tests/modules/test_base_vm.py::test_temporary_directory [32mPASSED[0m
tests/modules/test_base_vm.py::test_console [32mPASSED[0m
tests/modules/test_base_vm.py::test_change_console_port [32mPASSED[0m
tests/modules/test_base_vm.py::test_console_vnc_invalid [32mPASSED[0m
tests/modules/test_base_vm.py::test_close [32mPASSED[0m
tests/modules/test_base_vm.py::test_aux [32mPASSED[0m
tests/modules/test_base_vm.py::test_allocate_aux [32mPASSED[0m
tests/modules/test_base_vm.py::test_change_aux_port [32mPASSED[0m
tests/modules/test_manager.py::test_create_vm_new_topology [32mPASSED[0m
tests/modules/test_manager.py::test_create_twice_same_vm_new_topology [32mPASSED[0m
tests/modules/test_manager.py::test_create_vm_new_topology_without_uuid [32mPASSED[0m
tests/modules/test_manager.py::test_create_vm_old_topology [32mPASSED[0m
tests/modules/test_manager.py::test_get_abs_image_path [32mPASSED[0m
tests/modules/test_manager.py::test_get_abs_image_path_non_local [32mPASSED[0m
tests/modules/test_manager.py::test_get_relative_image_path [32mPASSED[0m
tests/modules/test_manager.py::test_get_relative_image_path_ova [32mPASSED[0m
tests/modules/test_manager.py::test_list_images [32mPASSED[0m
tests/modules/test_manager.py::test_list_images_recursives [32mPASSED[0m
tests/modules/test_manager.py::test_list_images_empty [32mPASSED[0m
tests/modules/test_manager.py::test_list_images_directory_not_exist [32mPASSED[0m
tests/modules/test_port_manager.py::test_reserve_tcp_port [32mPASSED[0m
tests/modules/test_port_manager.py::test_reserve_tcp_port_outside_range [32mPASSED[0m
tests/modules/test_port_manager.py::test_reserve_tcp_port_already_used_by_another_program [32mPASSED[0m
tests/modules/test_port_manager.py::test_reserve_tcp_port_already_used [32mPASSED[0m
tests/modules/test_port_manager.py::test_reserve_udp_port [32mPASSED[0m
tests/modules/test_port_manager.py::test_reserve_udp_port_outside_range [32mPASSED[0m
tests/modules/test_port_manager.py::test_release_udp_port [32mPASSED[0m
tests/modules/test_port_manager.py::test_find_unused_port [32mPASSED[0m
tests/modules/test_port_manager.py::test_find_unused_port_invalid_range [32mPASSED[0m
tests/modules/test_project.py::test_affect_uuid [32mPASSED[0m
tests/modules/test_project.py::test_path [32mPASSED[0m
tests/modules/test_project.py::test_init_path [32mPASSED[0m
tests/modules/test_project.py::test_changing_path_temporary_flag [32mPASSED[0m
tests/modules/test_project.py::test_temporary_path [32mPASSED[0m
tests/modules/test_project.py::test_remove_temporary_flag [32mPASSED[0m
tests/modules/test_project.py::test_changing_location_not_allowed [32mPASSED[0m
tests/modules/test_project.py::test_changing_path_not_allowed [32mPASSED[0m
tests/modules/test_project.py::test_changing_path_with_quote_not_allowed [32mPASSED[0m
tests/modules/test_project.py::test_json [32mPASSED[0m
tests/modules/test_project.py::test_vm_working_directory [32mPASSED[0m
tests/modules/test_project.py::test_mark_vm_for_destruction [32mPASSED[0m
tests/modules/test_project.py::test_commit [32mPASSED[0m
tests/modules/test_project.py::test_commit_permission_issue [32mPASSED[0m
tests/modules/test_project.py::test_project_delete [32mPASSED[0m
tests/modules/test_project.py::test_project_delete_permission_issue [32mPASSED[0m
tests/modules/test_project.py::test_project_add_vm [32mPASSED[0m
tests/modules/test_project.py::test_project_close [32mPASSED[0m
tests/modules/test_project.py::test_project_close_temporary_project [32mPASSED[0m
tests/modules/test_project.py::test_get_default_project_directory [32mPASSED[0m
tests/modules/test_project.py::test_clean_project_directory [32mPASSED[0m
tests/modules/test_project.py::test_list_files [32mPASSED[0m
tests/modules/test_project.py::test_export [32mPASSED[0m
tests/modules/test_project.py::test_export_fix_path [32mPASSED[0m
tests/modules/test_project.py::test_export_with_images [32mPASSED[0m
tests/modules/test_project.py::test_export_with_vm [32mPASSED[0m
tests/modules/test_project.py::test_import [32mPASSED[0m
tests/modules/test_project.py::test_import_with_images [32mPASSED[0m
tests/modules/test_project_manager.py::test_create_project [32mPASSED[0m
tests/modules/test_project_manager.py::test_project_not_found [32mPASSED[0m
tests/modules/docker/test_docker.py::test_query_success [32mPASSED[0m
tests/modules/docker/test_docker.py::test_query_error [32mPASSED[0m
tests/modules/docker/test_docker.py::test_query_error_json [32mPASSED[0m
tests/modules/docker/test_docker.py::test_list_images [32mPASSED[0m
tests/modules/docker/test_docker_vm.py::test_json [32mPASSED[0m
tests/modules/docker/test_docker_vm.py::test_start_command [32mPASSED[0m
tests/modules/docker/test_docker_vm.py::test_create [32mPASSED[0m
tests/modules/docker/test_docker_vm.py::test_create_with_tag [32mPASSED[0m
tests/modules/docker/test_docker_vm.py::test_create_vnc [32mPASSED[0m
tests/modules/docker/test_docker_vm.py::test_create_start_cmd [32mPASSED[0m
tests/modules/docker/test_docker_vm.py::test_create_environment [32mPASSED[0m
tests/modules/docker/test_docker_vm.py::test_create_image_not_available [32mPASSED[0m
tests/modules/docker/test_docker_vm.py::test_get_container_state [32mPASSED[0m
tests/modules/docker/test_docker_vm.py::test_is_running [32mPASSED[0m
tests/modules/docker/test_docker_vm.py::test_pause [32mPASSED[0m
tests/modules/docker/test_docker_vm.py::test_unpause [32mPASSED[0m
tests/modules/docker/test_docker_vm.py::test_start [32mPASSED[0m
tests/modules/docker/test_docker_vm.py::test_start_namespace_failed [32mPASSED[0m
tests/modules/docker/test_docker_vm.py::test_start_without_nio [32mPASSED[0m
tests/modules/docker/test_docker_vm.py::test_start_unpause [32mPASSED[0m
tests/modules/docker/test_docker_vm.py::test_restart [32mPASSED[0m
tests/modules/docker/test_docker_vm.py::test_stop [32mPASSED[0m
tests/modules/docker/test_docker_vm.py::test_stop_paused_container [32mPASSED[0m
tests/modules/docker/test_docker_vm.py::test_update [32mPASSED[0m
tests/modules/docker/test_docker_vm.py::test_update_vnc [32mPASSED[0m
tests/modules/docker/test_docker_vm.py::test_update_running [32mPASSED[0m
tests/modules/docker/test_docker_vm.py::test_delete [32mPASSED[0m
tests/modules/docker/test_docker_vm.py::test_close [32mPASSED[0m
tests/modules/docker/test_docker_vm.py::test_close_vnc [32mPASSED[0m
tests/modules/docker/test_docker_vm.py::test_get_namespace [32mPASSED[0m
tests/modules/docker/test_docker_vm.py::test_add_ubridge_connection [32mPASSED[0m
tests/modules/docker/test_docker_vm.py::test_add_ubridge_connection_none_nio [32mPASSED[0m
tests/modules/docker/test_docker_vm.py::test_add_ubridge_connection_invalid_adapter_number [32mPASSED[0m
tests/modules/docker/test_docker_vm.py::test_add_ubridge_connection_no_free_interface [32mPASSED[0m
tests/modules/docker/test_docker_vm.py::test_delete_ubridge_connection [32mPASSED[0m
tests/modules/docker/test_docker_vm.py::test_adapter_add_nio_binding [32mPASSED[0m
tests/modules/docker/test_docker_vm.py::test_adapter_add_nio_binding_invalid_adapter [32mPASSED[0m
tests/modules/docker/test_docker_vm.py::test_adapter_remove_nio_binding [32mPASSED[0m
tests/modules/docker/test_docker_vm.py::test_adapter_remove_nio_binding_invalid_adapter [32mPASSED[0m
tests/modules/docker/test_docker_vm.py::test_pull_image [32mPASSED[0m
tests/modules/docker/test_docker_vm.py::test_start_capture [32mPASSED[0m
tests/modules/docker/test_docker_vm.py::test_stop_capture [32mPASSED[0m
tests/modules/docker/test_docker_vm.py::test_get_log [32mPASSED[0m
tests/modules/docker/test_docker_vm.py::test_get_image_informations [32mPASSED[0m
tests/modules/docker/test_docker_vm.py::test_mount_binds [32mPASSED[0m
tests/modules/docker/test_docker_vm.py::test_start_vnc [32mPASSED[0m
tests/modules/docker/test_docker_vm.py::test_start_vnc_xvfb_missing [32mPASSED[0m
tests/modules/docker/test_docker_vm.py::test_start_aux [32mPASSED[0m
tests/modules/docker/test_docker_vm.py::test_create_network_interfaces [32mPASSED[0m
tests/modules/docker/test_docker_vm.py::test_fix_permission [32mPASSED[0m
tests/modules/dynamips/test_dynamips_manager.py::test_vm_invalid_dynamips_path [32mPASSED[0m
tests/modules/dynamips/test_dynamips_manager.py::test_vm_non_executable_dynamips_path [32mPASSED[0m
tests/modules/dynamips/test_dynamips_manager.py::test_get_dynamips_id [32mPASSED[0m
tests/modules/dynamips/test_dynamips_manager.py::test_take_dynamips_id [32mPASSED[0m
tests/modules/dynamips/test_dynamips_manager.py::test_release_dynamips_id [32mPASSED[0m
tests/modules/dynamips/test_dynamips_manager.py::test_project_closed [32mPASSED[0m
tests/modules/dynamips/test_dynamips_router.py::test_router [32mPASSED[0m
tests/modules/dynamips/test_dynamips_router.py::test_router_invalid_dynamips_path [32mPASSED[0m
tests/modules/iou/test_iou_manager.py::test_get_application_id [32mPASSED[0m
tests/modules/iou/test_iou_manager.py::test_get_application_id_multiple_project [32mPASSED[0m
tests/modules/iou/test_iou_manager.py::test_get_application_id_no_id_available [32mPASSED[0m
tests/modules/iou/test_iou_manager.py::test_get_images_directory [32mPASSED[0m
tests/modules/iou/test_iou_vm.py::test_vm [32mPASSED[0m
tests/modules/iou/test_iou_vm.py::test_vm_startup_config_content [32mPASSED[0m
tests/modules/iou/test_iou_vm.py::test_vm_invalid_iouyap_path [32mPASSED[0m
tests/modules/iou/test_iou_vm.py::test_start [32mPASSED[0m
tests/modules/iou/test_iou_vm.py::test_start_with_iourc [32mPASSED[0m
tests/modules/iou/test_iou_vm.py::test_rename_nvram_file [32mPASSED[0m
tests/modules/iou/test_iou_vm.py::test_stop [32mPASSED[0m
tests/modules/iou/test_iou_vm.py::test_reload [32mPASSED[0m
tests/modules/iou/test_iou_vm.py::test_close [32mPASSED[0m
tests/modules/iou/test_iou_vm.py::test_path [32mPASSED[0m
tests/modules/iou/test_iou_vm.py::test_path_12_location [32mPASSED[0m
tests/modules/iou/test_iou_vm.py::test_path_relative [32mPASSED[0m
tests/modules/iou/test_iou_vm.py::test_path_invalid_bin [32mPASSED[0m
tests/modules/iou/test_iou_vm.py::test_create_netmap_config [32mPASSED[0m
tests/modules/iou/test_iou_vm.py::test_build_command [32mPASSED[0m
tests/modules/iou/test_iou_vm.py::test_get_startup_config [32mPASSED[0m
tests/modules/iou/test_iou_vm.py::test_update_startup_config [32mPASSED[0m
tests/modules/iou/test_iou_vm.py::test_update_startup_config_empty [32mPASSED[0m
tests/modules/iou/test_iou_vm.py::test_update_startup_config_content_hostname [32mPASSED[0m
tests/modules/iou/test_iou_vm.py::test_change_name [32mPASSED[0m
tests/modules/iou/test_iou_vm.py::test_library_check [32mPASSED[0m
tests/modules/iou/test_iou_vm.py::test_enable_l1_keepalives [32mPASSED[0m
tests/modules/iou/test_iou_vm.py::test_start_capture [32mPASSED[0m
tests/modules/iou/test_iou_vm.py::test_stop_capture [32mPASSED[0m
tests/modules/iou/test_iou_vm.py::test_get_legacy_vm_workdir [32mPASSED[0m
tests/modules/iou/test_iou_vm.py::test_invalid_iou_file [32mPASSED[0m
tests/modules/iou/test_iou_vm.py::test_iourc_content [32mPASSED[0m
tests/modules/iou/test_iou_vm.py::test_iourc_content_fix_carriage_return [32mPASSED[0m
tests/modules/iou/test_iou_vm.py::test_extract_configs [32mPASSED[0m
tests/modules/qemu/test_qcow2.py::test_valid_base_file [32mPASSED[0m
tests/modules/qemu/test_qcow2.py::test_valid_linked_file [32mPASSED[0m
tests/modules/qemu/test_qcow2.py::test_invalid_file [32mPASSED[0m
tests/modules/qemu/test_qcow2.py::test_invalid_empty_file [32mPASSED[0m
tests/modules/qemu/test_qcow2.py::test_rebase [33mSKIPPED[0m
tests/modules/qemu/test_qemu_manager.py::test_get_qemu_version [32mPASSED[0m
tests/modules/qemu/test_qemu_manager.py::test_binary_list [32mPASSED[0m
tests/modules/qemu/test_qemu_manager.py::test_img_binary_list [32mPASSED[0m
tests/modules/qemu/test_qemu_manager.py::test_get_legacy_vm_workdir [32mPASSED[0m
tests/modules/qemu/test_qemu_manager.py::test_create_image_abs_path [32mPASSED[0m
tests/modules/qemu/test_qemu_manager.py::test_create_image_relative_path [32mPASSED[0m
tests/modules/qemu/test_qemu_manager.py::test_create_image_exist [32mPASSED[0m
tests/modules/qemu/test_qemu_manager.py::test_get_kvm_archs_kvm_ok [32mPASSED[0m
tests/modules/qemu/test_qemu_vm.py::test_vm [32mPASSED[0m
tests/modules/qemu/test_qemu_vm.py::test_vm_invalid_qemu_with_platform [32mPASSED[0m
tests/modules/qemu/test_qemu_vm.py::test_vm_invalid_qemu_without_platform [32mPASSED[0m
tests/modules/qemu/test_qemu_vm.py::test_is_running [32mPASSED[0m
tests/modules/qemu/test_qemu_vm.py::test_start [32mPASSED[0m
tests/modules/qemu/test_qemu_vm.py::test_stop [32mPASSED[0m
tests/modules/qemu/test_qemu_vm.py::test_termination_callback [32mPASSED[0m
tests/modules/qemu/test_qemu_vm.py::test_termination_callback_error [32mPASSED[0m
tests/modules/qemu/test_qemu_vm.py::test_reload [32mPASSED[0m
tests/modules/qemu/test_qemu_vm.py::test_suspend [32mPASSED[0m
tests/modules/qemu/test_qemu_vm.py::test_add_nio_binding_udp [32mPASSED[0m
tests/modules/qemu/test_qemu_vm.py::test_add_nio_binding_ethernet [32mPASSED[0m
tests/modules/qemu/test_qemu_vm.py::test_port_remove_nio_binding [32mPASSED[0m
tests/modules/qemu/test_qemu_vm.py::test_close [32mPASSED[0m
tests/modules/qemu/test_qemu_vm.py::test_set_qemu_path [32mPASSED[0m
tests/modules/qemu/test_qemu_vm.py::test_set_qemu_path_environ [32mPASSED[0m
tests/modules/qemu/test_qemu_vm.py::test_set_qemu_path_windows [32mPASSED[0m
tests/modules/qemu/test_qemu_vm.py::test_set_qemu_path_old_windows [32mPASSED[0m
tests/modules/qemu/test_qemu_vm.py::test_set_qemu_path_kvm_binary [32mPASSED[0m
tests/modules/qemu/test_qemu_vm.py::test_set_platform [32mPASSED[0m
tests/modules/qemu/test_qemu_vm.py::test_disk_options [32mPASSED[0m
tests/modules/qemu/test_qemu_vm.py::test_disk_options_multiple_disk [32mPASSED[0m
tests/modules/qemu/test_qemu_vm.py::test_set_process_priority [32mPASSED[0m
tests/modules/qemu/test_qemu_vm.py::test_set_process_priority_normal [32mPASSED[0m
tests/modules/qemu/test_qemu_vm.py::test_json [32mPASSED[0m
tests/modules/qemu/test_qemu_vm.py::test_control_vm [32mPASSED[0m
tests/modules/qemu/test_qemu_vm.py::test_control_vm_expect_text [32mPASSED[0m
tests/modules/qemu/test_qemu_vm.py::test_build_command [32mPASSED[0m
tests/modules/qemu/test_qemu_vm.py::test_build_command_kvm [32mPASSED[0m
tests/modules/qemu/test_qemu_vm.py::test_build_command_kvm_2_4 [32mPASSED[0m
tests/modules/qemu/test_qemu_vm.py::test_build_command_without_display [32mPASSED[0m
tests/modules/qemu/test_qemu_vm.py::test_build_command_two_adapters [32mPASSED[0m
tests/modules/qemu/test_qemu_vm.py::test_build_command_two_adapters_mac_address [32mPASSED[0m
tests/modules/qemu/test_qemu_vm.py::test_build_command_with_invalid_options [32mPASSED[0m
tests/modules/qemu/test_qemu_vm.py::test_hda_disk_image [32mPASSED[0m
tests/modules/qemu/test_qemu_vm.py::test_hda_disk_image_ova [32mPASSED[0m
tests/modules/qemu/test_qemu_vm.py::test_hdb_disk_image [32mPASSED[0m
tests/modules/qemu/test_qemu_vm.py::test_hdc_disk_image [32mPASSED[0m
tests/modules/qemu/test_qemu_vm.py::test_hdd_disk_image [32mPASSED[0m
tests/modules/qemu/test_qemu_vm.py::test_initrd [32mPASSED[0m
tests/modules/qemu/test_qemu_vm.py::test_initrd_asa [32mPASSED[0m
tests/modules/qemu/test_qemu_vm.py::test_options [32mPASSED[0m
tests/modules/qemu/test_qemu_vm.py::test_options_windows [32mPASSED[0m
tests/modules/qemu/test_qemu_vm.py::test_get_qemu_img [32mPASSED[0m
tests/modules/qemu/test_qemu_vm.py::test_get_qemu_img_not_exist [32mPASSED[0m
tests/modules/qemu/test_qemu_vm.py::test_run_with_kvm_darwin [32mPASSED[0m
tests/modules/qemu/test_qemu_vm.py::test_run_with_kvm_windows [32mPASSED[0m
tests/modules/qemu/test_qemu_vm.py::test_run_with_kvm_linux [32mPASSED[0m
tests/modules/qemu/test_qemu_vm.py::test_run_with_kvm_linux_options_no_kvm [32mPASSED[0m
tests/modules/qemu/test_qemu_vm.py::test_run_with_kvm_not_x86 [32mPASSED[0m
tests/modules/qemu/test_qemu_vm.py::test_run_with_kvm_linux_dev_kvm_missing [32mPASSED[0m
tests/modules/virtualbox/test_virtualbox_manager.py::test_vm_invalid_vboxmanage_path [32mPASSED[0m
tests/modules/virtualbox/test_virtualbox_manager.py::test_vm_non_executable_vboxmanage_path [32mPASSED[0m
tests/modules/virtualbox/test_virtualbox_manager.py::test_vm_invalid_executable_name_vboxmanage_path [32mPASSED[0m
tests/modules/virtualbox/test_virtualbox_manager.py::test_vboxmanage_path [32mPASSED[0m
tests/modules/virtualbox/test_virtualbox_manager.py::test_list_images [32mPASSED[0m
tests/modules/virtualbox/test_virtualbox_vm.py::test_vm [32mPASSED[0m
tests/modules/virtualbox/test_virtualbox_vm.py::test_vm_valid_virtualbox_api_version [32mPASSED[0m
tests/modules/virtualbox/test_virtualbox_vm.py::test_vm_invalid_virtualbox_api_version [32mPASSED[0m
tests/modules/virtualbox/test_virtualbox_vm.py::test_vm_adapter_add_nio_binding_adapter_not_exist [32mPASSED[0m
tests/modules/virtualbox/test_virtualbox_vm.py::test_json [32mPASSED[0m
tests/modules/vmware/test_vmware_manager.py::test_parse_vmware_file [32mPASSED[0m
tests/modules/vmware/test_vmware_vm.py::test_vm [32mPASSED[0m
tests/modules/vmware/test_vmware_vm.py::test_json [32mPASSED[0m
tests/modules/vmware/test_vmware_vm.py::test_start_capture [32mPASSED[0m
tests/modules/vmware/test_vmware_vm.py::test_stop_capture [32mPASSED[0m
tests/modules/vpcs/test_vpcs_manager.py::test_get_mac_id [32mPASSED[0m
tests/modules/vpcs/test_vpcs_manager.py::test_get_mac_id_multiple_project [32mPASSED[0m
tests/modules/vpcs/test_vpcs_manager.py::test_get_mac_id_no_id_available [32mPASSED[0m
tests/modules/vpcs/test_vpcs_vm.py::test_vm [32mPASSED[0m
tests/modules/vpcs/test_vpcs_vm.py::test_vm_check_vpcs_version [32mPASSED[0m
tests/modules/vpcs/test_vpcs_vm.py::test_vm_check_vpcs_version_0_6_1 [32mPASSED[0m
tests/modules/vpcs/test_vpcs_vm.py::test_vm_invalid_vpcs_version [32mPASSED[0m
tests/modules/vpcs/test_vpcs_vm.py::test_vm_invalid_vpcs_path [32mPASSED[0m
tests/modules/vpcs/test_vpcs_vm.py::test_start [32mPASSED[0m
tests/modules/vpcs/test_vpcs_vm.py::test_start_0_6_1 [32mPASSED[0m
tests/modules/vpcs/test_vpcs_vm.py::test_stop [32mPASSED[0m
tests/modules/vpcs/test_vpcs_vm.py::test_reload [32mPASSED[0m
tests/modules/vpcs/test_vpcs_vm.py::test_add_nio_binding_udp [32mPASSED[0m
tests/modules/vpcs/test_vpcs_vm.py::test_add_nio_binding_tap [32mPASSED[0m
tests/modules/vpcs/test_vpcs_vm.py::test_port_remove_nio_binding [32mPASSED[0m
tests/modules/vpcs/test_vpcs_vm.py::test_update_startup_script [32mPASSED[0m
tests/modules/vpcs/test_vpcs_vm.py::test_update_startup_script_h [32mPASSED[0m
tests/modules/vpcs/test_vpcs_vm.py::test_get_startup_script [32mPASSED[0m
tests/modules/vpcs/test_vpcs_vm.py::test_get_startup_script_using_default_script [32mPASSED[0m
tests/modules/vpcs/test_vpcs_vm.py::test_change_name [32mPASSED[0m
tests/modules/vpcs/test_vpcs_vm.py::test_close [32mPASSED[0m
tests/utils/test_asyncio.py::test_wait_run_in_executor [32mPASSED[0m
tests/utils/test_asyncio.py::test_exception_wait_run_in_executor [32mPASSED[0m
tests/utils/test_asyncio.py::test_subprocess_check_output [32mPASSED[0m
tests/utils/test_asyncio.py::test_wait_for_process_termination [32mPASSED[0m
tests/utils/test_asyncio.py::test_lock_decorator [32mPASSED[0m
tests/utils/test_images.py::test_md5sum [32mPASSED[0m
tests/utils/test_images.py::test_md5sum_existing_digest [32mPASSED[0m
tests/utils/test_images.py::test_md5sum_existing_digest_but_missing_image [32mPASSED[0m
tests/utils/test_images.py::test_md5sum_none [32mPASSED[0m
tests/utils/test_images.py::test_remove_checksum [32mPASSED[0m
tests/utils/test_interfaces.py::test_interfaces [32mPASSED[0m
tests/utils/test_interfaces.py::test_is_interface_up [32mPASSED[0m
tests/web/test_documentation.py::test_documentation_write Build config
Build docker
Build dynamips_device
Build dynamips_vm
Build file
Build gns3server.handlers.index
Build gns3server.handlers.upload
Build iou
Build network
Build project
Build qemu
Build server
Build version
Build virtualbox
Build vmware
Build vpcs
[32mPASSED[0m
tests/web/test_logger.py::test_init_logger [32mPASSED[0m
tests/web/test_logger.py::test_init_logger_quiet WARN1
ERROR1
CRITICAL1
[32mPASSED[0m

[1m[33m========== 407 passed, 2 skipped, 2 pytest-warnings in 20.48 seconds ===========[0m

travis_time:end:05085e64:start=1492086436133324614,finish=1492086458156733922,duration=22023409308[0K
[32;1mThe command "py.test -v -s tests" exited with 0.[0m
travis_fold:start:cache.2[0Kstore build cache
travis_time:start:16e8ca9b[0K
travis_time:end:16e8ca9b:start=1492086458162335825,finish=1492086458167011762,duration=4675937[0Ktravis_time:start:041f7668[0K[32;1mchange detected (content changed, file is created, or file is deleted):
/home/travis/.cache/pip/http/0/a/5/e/a/0a5ea25d60ee4ac7b500a33fe7f830a41682c55e0af7554ac06ea8d0
/home/travis/.cache/pip/http/0/e/7/b/9/0e7b99547a0247a24df2175f35e166cf96f0194417e99b4851dbf306
/home/travis/.cache/pip/http/2/3/9/9/c/2399ce14e5d071a00b24636db2a7d8f9ef4a63fbd2d60206408e2290
/home/travis/.cache/pip/http/2/f/6/0/e/2f60ee2e6b2f8d9d74debb0760385405e98f6d110bddba8ef79ec89c
/home/travis/.cache/pip/http/6/3/c/4/2/63c426d150091b9663b3d4923999b229a56ede976ab93677382d9562
/home/travis/.cache/pip/http/9/8/6/9/9/98699498902615272ab771867239623248aaa33dfc970e0d77ae93e6
/home/travis/.cache/pip/http/9/e/6/1/9/9e61964f51d8a05a20ecf21eef694877f28cb654a123ce1316ff77e5
/home/travis/.cache/pip/http/a/9/5/b/1/a95b1e366422caa07b5ba5fc79636026b57716e26d614e2427980b9a
/home/travis/.cache/pip/http/a/c/1/0/1/ac101e8cf49601082604b02a8a13937b06fded9144495898d0d80359
/home/travis/.cache/pip/http/a/e/0/9/6/ae0963a2158bd11ad096f4d0ecdb916b8d8cead4cefcb63a552de4a4
/home/travis/.cache/pip/http/c/2/9/1/2/c2
[0m
[32;1m...
[0m
[32;1mchanges detected, packing new archive[0m
[32;1muploading archive[0m

travis_time:end:041f7668:start=1492086458172040268,finish=1492086459930398219,duration=1758357951[0Ktravis_fold:end:cache.2[0K[33;1mSkipping a deployment with the pypi provider because this is not a tagged commit[0m

Done. Your build exited with 0.
