Using worker: worker-linux-docker-cdc7a134.prod.travis-ci.org:travis-linux-16

travis_fold:start:system_info[0K[33;1mBuild system information[0m
Build language: python
Build group: stable
Build dist: precise
[34m[1mBuild image provisioning date and time[0m
Thu Feb  5 15:09:33 UTC 2015
[34m[1mOperating System Details[0m
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise
[34m[1mLinux Version[0m
3.13.0-29-generic
[34m[1mCookbooks Version[0m
a68419e https://github.com/travis-ci/travis-cookbooks/tree/a68419e
[34m[1mGCC version[0m
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[34m[1mLLVM version[0m
clang version 3.4 (tags/RELEASE_34/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
[34m[1mPre-installed Ruby versions[0m
ruby-1.9.3-p551
[34m[1mPre-installed Node.js versions[0m
v0.10.36
[34m[1mPre-installed Go versions[0m
1.4.1
[34m[1mRedis version[0m
redis-server 2.8.19
[34m[1mriak version[0m
2.0.2
[34m[1mMongoDB version[0m
MongoDB 2.4.12
[34m[1mCouchDB version[0m
couchdb 1.6.1
[34m[1mNeo4j version[0m
1.9.4
[34m[1mRabbitMQ Version[0m
3.4.3
[34m[1mElasticSearch version[0m
1.4.0
[34m[1mInstalled Sphinx versions[0m
2.0.10
2.1.9
2.2.6
[34m[1mDefault Sphinx version[0m
2.2.6
[34m[1mInstalled Firefox version[0m
firefox 31.0esr
[34m[1mPhantomJS version[0m
1.9.8
[34m[1mant -version[0m
Apache Ant(TM) version 1.8.2 compiled on December 3 2011
[34m[1mmvn -version[0m
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T17:29:23+00:00)
Maven home: /usr/local/maven
Java version: 1.7.0_76, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-oracle/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "3.13.0-29-generic", arch: "amd64", family: "unix"
travis_fold:end:system_info[0K
travis_fold:start:git.checkout[0Ktravis_time:start:08ba156c[0K$ git clone --depth=50 --branch=docupdate https://github.com/Unidata/netcdf4-python.git Unidata/netcdf4-python
Cloning into 'Unidata/netcdf4-python'...
remote: Counting objects: 754, done.[K
remote: Compressing objects:   0% (1/387)   [Kremote: Compressing objects:   1% (4/387)   [Kremote: Compressing objects:   2% (8/387)   [Kremote: Compressing objects:   3% (12/387)   [Kremote: Compressing objects:   4% (16/387)   [Kremote: Compressing objects:   5% (20/387)   [Kremote: Compressing objects:   6% (24/387)   [Kremote: Compressing objects:   7% (28/387)   [Kremote: Compressing objects:   8% (31/387)   [Kremote: Compressing objects:   9% (35/387)   [Kremote: Compressing objects:  10% (39/387)   [Kremote: Compressing objects:  11% (43/387)   [Kremote: Compressing objects:  12% (47/387)   [Kremote: Compressing objects:  13% (51/387)   [Kremote: Compressing objects:  14% (55/387)   [Kremote: Compressing objects:  15% (59/387)   [Kremote: Compressing objects:  16% (62/387)   [Kremote: Compressing objects:  17% (66/387)   [Kremote: Compressing objects:  18% (70/387)   [Kremote: Compressing objects:  19% (74/387)   [Kremote: Compressing objects:  20% (78/387)   [Kremote: Compressing objects:  21% (82/387)   [Kremote: Compressing objects:  22% (86/387)   [Kremote: Compressing objects:  23% (90/387)   [Kremote: Compressing objects:  24% (93/387)   [Kremote: Compressing objects:  25% (97/387)   [Kremote: Compressing objects:  26% (101/387)   [Kremote: Compressing objects:  27% (105/387)   [Kremote: Compressing objects:  28% (109/387)   [Kremote: Compressing objects:  29% (113/387)   [Kremote: Compressing objects:  30% (117/387)   [Kremote: Compressing objects:  31% (120/387)   [Kremote: Compressing objects:  32% (124/387)   [Kremote: Compressing objects:  33% (128/387)   [Kremote: Compressing objects:  34% (132/387)   [Kremote: Compressing objects:  35% (136/387)   [Kremote: Compressing objects:  35% (139/387)   [Kremote: Compressing objects:  36% (140/387)   [Kremote: Compressing objects:  37% (144/387)   [Kremote: Compressing objects:  38% (148/387)   [Kremote: Compressing objects:  38% (150/387)   [Kremote: Compressing objects:  39% (151/387)   [Kremote: Compressing objects:  40% (155/387)   [Kremote: Compressing objects:  41% (159/387)   [Kremote: Compressing objects:  42% (163/387)   [Kremote: Compressing objects:  43% (167/387)   [Kremote: Compressing objects:  44% (171/387)   [Kremote: Compressing objects:  45% (175/387)   [Kremote: Compressing objects:  46% (179/387)   [Kremote: Compressing objects:  47% (182/387)   [Kremote: Compressing objects:  48% (186/387)   [Kremote: Compressing objects:  49% (190/387)   [Kremote: Compressing objects:  50% (194/387)   [Kremote: Compressing objects:  51% (198/387)   [Kremote: Compressing objects:  52% (202/387)   [Kremote: Compressing objects:  53% (206/387)   [Kremote: Compressing objects:  54% (209/387)   [Kremote: Compressing objects:  55% (213/387)   [Kremote: Compressing objects:  56% (217/387)   [Kremote: Compressing objects:  57% (221/387)   [Kremote: Compressing objects:  58% (225/387)   [Kremote: Compressing objects:  59% (229/387)   [Kremote: Compressing objects:  60% (233/387)   [Kremote: Compressing objects:  61% (237/387)   [Kremote: Compressing objects:  62% (240/387)   [Kremote: Compressing objects:  63% (244/387)   [Kremote: Compressing objects:  64% (248/387)   [Kremote: Compressing objects:  65% (252/387)   [Kremote: Compressing objects:  66% (256/387)   [Kremote: Compressing objects:  67% (260/387)   [Kremote: Compressing objects:  68% (264/387)   [Kremote: Compressing objects:  69% (268/387)   [Kremote: Compressing objects:  70% (271/387)   [Kremote: Compressing objects:  71% (275/387)   [Kremote: Compressing objects:  72% (279/387)   [Kremote: Compressing objects:  73% (283/387)   [Kremote: Compressing objects:  74% (287/387)   [Kremote: Compressing objects:  75% (291/387)   [Kremote: Compressing objects:  76% (295/387)   [Kremote: Compressing objects:  77% (298/387)   [Kremote: Compressing objects:  78% (302/387)   [Kremote: Compressing objects:  79% (306/387)   [Kremote: Compressing objects:  80% (310/387)   [Kremote: Compressing objects:  81% (314/387)   [Kremote: Compressing objects:  82% (318/387)   [Kremote: Compressing objects:  83% (322/387)   [Kremote: Compressing objects:  84% (326/387)   [Kremote: Compressing objects:  85% (329/387)   [Kremote: Compressing objects:  86% (333/387)   [Kremote: Compressing objects:  87% (337/387)   [Kremote: Compressing objects:  88% (341/387)   [Kremote: Compressing objects:  89% (345/387)   [Kremote: Compressing objects:  90% (349/387)   [Kremote: Compressing objects:  91% (353/387)   [Kremote: Compressing objects:  92% (357/387)   [Kremote: Compressing objects:  93% (360/387)   [Kremote: Compressing objects:  94% (364/387)   [Kremote: Compressing objects:  95% (368/387)   [Kremote: Compressing objects:  96% (372/387)   [Kremote: Compressing objects:  97% (376/387)   [Kremote: Compressing objects:  98% (380/387)   [Kremote: Compressing objects:  99% (384/387)   [Kremote: Compressing objects: 100% (387/387)   [Kremote: Compressing objects: 100% (387/387), done.[K
Receiving objects:   0% (1/754)   Receiving objects:   1% (8/754)   Receiving objects:   2% (16/754)   Receiving objects:   3% (23/754)   Receiving objects:   4% (31/754)   Receiving objects:   5% (38/754)   Receiving objects:   6% (46/754)   Receiving objects:   7% (53/754)   Receiving objects:   8% (61/754)   Receiving objects:   9% (68/754)   Receiving objects:  10% (76/754)   Receiving objects:  11% (83/754)   Receiving objects:  12% (91/754)   Receiving objects:  13% (99/754)   Receiving objects:  14% (106/754)   Receiving objects:  15% (114/754)   Receiving objects:  16% (121/754)   Receiving objects:  17% (129/754)   Receiving objects:  18% (136/754)   Receiving objects:  19% (144/754)   Receiving objects:  20% (151/754)   Receiving objects:  21% (159/754)   Receiving objects:  22% (166/754)   Receiving objects:  23% (174/754)   Receiving objects:  24% (181/754)   Receiving objects:  25% (189/754)   Receiving objects:  25% (195/754), 28.18 MiB | 28.12 MiB/s   Receiving objects:  26% (197/754), 28.18 MiB | 28.12 MiB/s   Receiving objects:  26% (199/754), 61.07 MiB | 30.48 MiB/s   Receiving objects:  26% (203/754), 93.73 MiB | 31.18 MiB/s   Receiving objects:  27% (204/754), 93.73 MiB | 31.18 MiB/s   Receiving objects:  27% (204/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  28% (212/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  29% (219/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  30% (227/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  31% (234/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  32% (242/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  33% (249/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  34% (257/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  35% (264/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  36% (272/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  37% (279/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  38% (287/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  39% (295/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  40% (302/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  41% (310/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  42% (317/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  43% (325/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  44% (332/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  45% (340/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  46% (347/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  47% (355/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  48% (362/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  49% (370/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  50% (377/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  51% (385/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  52% (393/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  53% (400/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  54% (408/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  55% (415/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  56% (423/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  57% (430/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  58% (438/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  59% (445/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  60% (453/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  61% (460/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  62% (468/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  63% (476/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  64% (483/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  65% (491/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  66% (498/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  67% (506/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  68% (513/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  69% (521/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  70% (528/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  71% (536/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  72% (543/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  73% (551/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  74% (558/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  75% (566/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  76% (574/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  77% (581/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  78% (589/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  79% (596/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  80% (604/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  81% (611/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  82% (619/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  83% (626/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  84% (634/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  85% (641/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  86% (649/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  87% (656/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  88% (664/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  89% (672/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  90% (679/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  91% (687/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  92% (694/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  93% (702/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  94% (709/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  95% (717/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  96% (724/754), 123.99 MiB | 30.94 MiB/s   remote: Total 754 (delta 418), reused 616 (delta 328), pack-reused 0[K
Receiving objects:  97% (732/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  98% (739/754), 123.99 MiB | 30.94 MiB/s   Receiving objects:  99% (747/754), 123.99 MiB | 30.94 MiB/s   Receiving objects: 100% (754/754), 123.99 MiB | 30.94 MiB/s   Receiving objects: 100% (754/754), 134.49 MiB | 30.94 MiB/s, done.
Resolving deltas:   0% (0/418)   Resolving deltas:  32% (137/418)   Resolving deltas:  33% (142/418)   Resolving deltas:  42% (179/418)   Resolving deltas:  43% (180/418)   Resolving deltas:  44% (188/418)   Resolving deltas:  45% (190/418)   Resolving deltas:  46% (194/418)   Resolving deltas:  47% (197/418)   Resolving deltas:  48% (202/418)   Resolving deltas:  50% (209/418)   Resolving deltas:  56% (235/418)   Resolving deltas:  57% (242/418)   Resolving deltas:  60% (252/418)   Resolving deltas:  62% (262/418)   Resolving deltas:  63% (267/418)   Resolving deltas:  67% (284/418)   Resolving deltas:  68% (286/418)   Resolving deltas:  69% (290/418)   Resolving deltas:  70% (296/418)   Resolving deltas:  71% (297/418)   Resolving deltas:  72% (302/418)   Resolving deltas:  73% (308/418)   Resolving deltas:  74% (310/418)   Resolving deltas:  75% (315/418)   Resolving deltas:  76% (321/418)   Resolving deltas:  77% (322/418)   Resolving deltas:  78% (328/418)   Resolving deltas:  79% (331/418)   Resolving deltas:  88% (372/418)   Resolving deltas: 100% (418/418)   Resolving deltas: 100% (418/418), done.
Checking connectivity... done.
travis_time:end:08ba156c:start=1450907081083021900,finish=1450907096999636159,duration=15916614259[0K$ cd Unidata/netcdf4-python
$ git checkout -qf 33be742a3d2770c70b9c28a17a1ada2d2c848f23
travis_fold:end:git.checkout[0Ktravis_fold:start:apt[0K[33;1mInstalling APT Packages (BETA)[0m
$ export DEBIAN_FRONTEND=noninteractive
travis_time:start:05990afc[0K$ sudo -E apt-get -yq update &>> ~/apt-get-update.log
travis_time:end:05990afc:start=1450907097757420409,finish=1450907112700485634,duration=14943065225[0Ktravis_time:start:08c550e3[0K$ sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install libhdf5-serial-dev netcdf-bin libnetcdf-dev
Reading package lists...
Building dependency tree...
Reading state information...
Suggested packages:
  libhdf5-doc netcdf-doc
The following NEW packages will be installed:
  libhdf5-serial-dev libnetcdf-dev netcdf-bin
0 upgraded, 3 newly installed, 0 to remove and 209 not upgraded.
Need to get 3,107 kB of archives.
After this operation, 20.4 MB of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu/ precise/universe libhdf5-serial-dev amd64 1.8.4-patch1-3ubuntu2 [2,278 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu/ precise/universe libnetcdf-dev amd64 1:4.1.1-6 [644 kB]
Get:3 http://us.archive.ubuntu.com/ubuntu/ precise/universe netcdf-bin amd64 1:4.1.1-6 [185 kB]
Fetched 3,107 kB in 0s (16.8 MB/s)
Selecting previously unselected package libhdf5-serial-dev.
(Reading database ... (Reading database ... 5%(Reading database ... 10%(Reading database ... 15%(Reading database ... 20%(Reading database ... 25%(Reading database ... 30%(Reading database ... 35%(Reading database ... 40%(Reading database ... 45%(Reading database ... 50%(Reading database ... 55%(Reading database ... 60%(Reading database ... 65%(Reading database ... 70%(Reading database ... 75%(Reading database ... 80%(Reading database ... 85%(Reading database ... 90%(Reading database ... 95%(Reading database ... 100%(Reading database ... 72431 files and directories currently installed.)
Unpacking libhdf5-serial-dev (from .../libhdf5-serial-dev_1.8.4-patch1-3ubuntu2_amd64.deb) ...
Selecting previously unselected package libnetcdf-dev.
Unpacking libnetcdf-dev (from .../libnetcdf-dev_1%3a4.1.1-6_amd64.deb) ...
Selecting previously unselected package netcdf-bin.
Unpacking netcdf-bin (from .../netcdf-bin_1%3a4.1.1-6_amd64.deb) ...
Processing triggers for man-db ...
Setting up libhdf5-serial-dev (1.8.4-patch1-3ubuntu2) ...
Setting up libnetcdf-dev (1:4.1.1-6) ...
Setting up netcdf-bin (1:4.1.1-6) ...
travis_time:end:08c550e3:start=1450907112703901004,finish=1450907122420276893,duration=9716375889[0Ktravis_fold:end:apt[0K
[33;1mThis job is running on container-based infrastructure, which does not allow use of 'sudo', setuid and setguid executables.[0m
[33;1mIf you require sudo, add 'sudo: required' to your .travis.yml[0m
[33;1mSee http://docs.travis-ci.com/user/workers/container-based-infrastructure/ for details.[0m

[33;1mSetting environment variables from .travis.yml[0m
$ export DEPENDS="numpy cython"
$ export NO_NET=1
$ export DEPENDS="numpy ordereddict"

travis_time:start:031d19e7[0K$ source ~/virtualenv/python2.6/bin/activate
travis_time:end:031d19e7:start=1450907125132361896,finish=1450907125136454145,duration=4092249[0K$ python --version
Python 2.6.9
$ pip --version
pip 6.0.7 from /home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages (python 2.6)
travis_fold:start:before_install[0Ktravis_time:start:09045669[0K$ pip install $DEPENDS
[33mYou are using pip version 6.0.7, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.[0m
Requirement already satisfied (use --upgrade to upgrade): numpy in /home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages
Collecting ordereddict
  Downloading ordereddict-1.1.tar.gz
    /tmp/pip-build-URGP7s/ordereddict/setup.py:12: DeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
Installing collected packages: ordereddict
  Running setup.py install for ordereddict
    /home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/setuptools/command/egg_info.py:171: DeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
      writer = ep.load(installer=installer)
Successfully installed ordereddict-1.1
travis_time:end:09045669:start=1450907125591385576,finish=1450907126348398630,duration=757013054[0Ktravis_fold:end:before_install[0Ktravis_fold:start:install.1[0Ktravis_time:start:22aa0c18[0K$ python setup.py build
reading from setup.cfg...
using nc-config ...
using netcdf library version 4.1.1
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.6
creating build/lib.linux-x86_64-2.6/netcdftime
copying netcdftime/__init__.py -> build/lib.linux-x86_64-2.6/netcdftime
copying netcdftime/netcdftime.py -> build/lib.linux-x86_64-2.6/netcdftime
creating build/lib.linux-x86_64-2.6/netCDF4
copying netCDF4/__init__.py -> build/lib.linux-x86_64-2.6/netCDF4
copying netCDF4/utils.py -> build/lib.linux-x86_64-2.6/netCDF4
running build_ext
building 'netCDF4._netCDF4' extension
creating build/temp.linux-x86_64-2.6
creating build/temp.linux-x86_64-2.6/netCDF4
gcc -pthread -fno-strict-aliasing -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/include -I/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/numpy/core/include -I/opt/python/2.6.9/include/python2.6 -c netCDF4/_netCDF4.c -o build/temp.linux-x86_64-2.6/netCDF4/_netCDF4.o
In file included from /home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1804:0,
                 from /home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:17,
                 from /home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from netCDF4/_netCDF4.c:243:
/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
netCDF4/_netCDF4.c: In function ‘__pyx_f_7netCDF4_8_netCDF4__set_att’:
netCDF4/_netCDF4.c:6125:7: warning: passing argument 5 of ‘nc_put_att_string’ from incompatible pointer type [enabled by default]
/usr/include/netcdf.h:956:1: note: expected ‘const char **’ but argument is of type ‘char **’
netCDF4/_netCDF4.c: In function ‘__pyx_f_7netCDF4_8_netCDF4__find_cmptype’:
netCDF4/_netCDF4.c:81316:34: warning: ‘__pyx_v_xtype’ may be used uninitialized in this function [-Wuninitialized]
netCDF4/_netCDF4.c:50940:11: note: ‘__pyx_v_xtype’ was declared here
netCDF4/_netCDF4.c: In function ‘__pyx_f_7netCDF4_8_netCDF4__get_types’:
netCDF4/_netCDF4.c:6826:21: warning: ‘__pyx_v_typeids’ may be used uninitialized in this function [-Wuninitialized]
netCDF4/_netCDF4.c: In function ‘__pyx_pw_7netCDF4_8_netCDF4_8Variable_1__init__’:
netCDF4/_netCDF4.c:27171:20: warning: ‘__pyx_v_dimids’ may be used uninitialized in this function [-Wuninitialized]
netCDF4/_netCDF4.c:25771:8: note: ‘__pyx_v_dimids’ was declared here
gcc -pthread -shared build/temp.linux-x86_64-2.6/netCDF4/_netCDF4.o -L/usr/lib -L/opt/python/2.6.9/lib -Wl,-R/usr/lib -lnetcdf -lpython2.6 -o build/lib.linux-x86_64-2.6/netCDF4/_netCDF4.so
building 'netcdftime._datetime' extension
creating build/temp.linux-x86_64-2.6/netcdftime
gcc -pthread -fno-strict-aliasing -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/opt/python/2.6.9/include/python2.6 -c netcdftime/_datetime.c -o build/temp.linux-x86_64-2.6/netcdftime/_datetime.o
gcc -pthread -shared build/temp.linux-x86_64-2.6/netcdftime/_datetime.o -L/opt/python/2.6.9/lib -lpython2.6 -o build/lib.linux-x86_64-2.6/netcdftime/_datetime.so
travis_time:end:22aa0c18:start=1450907126352369617,finish=1450907169818735329,duration=43466365712[0Ktravis_fold:end:install.1[0Ktravis_fold:start:install.2[0Ktravis_time:start:2254bc77[0K$ python setup.py install
reading from setup.cfg...
using nc-config ...
using netcdf library version 4.1.1
running install
running bdist_egg
running egg_info
creating netCDF4.egg-info
/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/setuptools/command/egg_info.py:171: DeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  writer = ep.load(installer=installer)
writing requirements to netCDF4.egg-info/requires.txt
writing netCDF4.egg-info/PKG-INFO
writing top-level names to netCDF4.egg-info/top_level.txt
writing dependency_links to netCDF4.egg-info/dependency_links.txt
writing entry points to netCDF4.egg-info/entry_points.txt
writing manifest file 'netCDF4.egg-info/SOURCES.txt'
reading manifest file 'netCDF4.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'netCDF4.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/netcdftime
copying build/lib.linux-x86_64-2.6/netcdftime/__init__.py -> build/bdist.linux-x86_64/egg/netcdftime
copying build/lib.linux-x86_64-2.6/netcdftime/netcdftime.py -> build/bdist.linux-x86_64/egg/netcdftime
copying build/lib.linux-x86_64-2.6/netcdftime/_datetime.so -> build/bdist.linux-x86_64/egg/netcdftime
creating build/bdist.linux-x86_64/egg/netCDF4
copying build/lib.linux-x86_64-2.6/netCDF4/__init__.py -> build/bdist.linux-x86_64/egg/netCDF4
copying build/lib.linux-x86_64-2.6/netCDF4/utils.py -> build/bdist.linux-x86_64/egg/netCDF4
copying build/lib.linux-x86_64-2.6/netCDF4/_netCDF4.so -> build/bdist.linux-x86_64/egg/netCDF4
byte-compiling build/bdist.linux-x86_64/egg/netcdftime/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/netcdftime/netcdftime.py to netcdftime.pyc
byte-compiling build/bdist.linux-x86_64/egg/netCDF4/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/netCDF4/utils.py to utils.pyc
creating stub loader for netCDF4/_netCDF4.so
creating stub loader for netcdftime/_datetime.so
byte-compiling build/bdist.linux-x86_64/egg/netCDF4/_netCDF4.py to _netCDF4.pyc
byte-compiling build/bdist.linux-x86_64/egg/netcdftime/_datetime.py to _datetime.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying netCDF4.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying netCDF4.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying netCDF4.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying netCDF4.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying netCDF4.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying netCDF4.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/netCDF4-1.2.2-py2.6-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing netCDF4-1.2.2-py2.6-linux-x86_64.egg
Copying netCDF4-1.2.2-py2.6-linux-x86_64.egg to /home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages
Adding netCDF4 1.2.2 to easy-install.pth file
Installing ncinfo script to /home/travis/virtualenv/python2.6.9/bin
Installing nc4tonc3 script to /home/travis/virtualenv/python2.6.9/bin
Installing nc3tonc4 script to /home/travis/virtualenv/python2.6.9/bin

Installed /home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/netCDF4-1.2.2-py2.6-linux-x86_64.egg
Processing dependencies for netCDF4==1.2.2
Searching for numpy==1.9.1
Best match: numpy 1.9.1
Adding numpy 1.9.1 to easy-install.pth file

Using /home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages
Finished processing dependencies for netCDF4==1.2.2
travis_time:end:2254bc77:start=1450907169824053405,finish=1450907170370935976,duration=546882571[0Ktravis_fold:end:install.2[0Ktravis_time:start:307a41fc[0K$ cd test
travis_time:end:307a41fc:start=1450907170376305529,finish=1450907170380587856,duration=4282327[0K
[32;1mThe command "cd test" exited with 0.[0m
travis_time:start:13a230db[0K$ python run_all.py
/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/pkg_resources/__init__.py:1222: UserWarning: /home/travis/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
not running tst_unicode3.py ...
not running tst_diskless.py ...
not running tst_dap.py ...

netcdf4-python version: 1.2.2
HDF5 lib version:       1.8.4-patch1
netcdf lib version:     4.1.1
numpy version           1.9.1
EEEEEEEEEEE.....EEEEEEEEEEEEEEEEEEEEE.EEEEEEEEEEEEEEEEEEEEEE...........EEEEE
======================================================================
ERROR: testing attributes
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_atts.py", line 39, in setUp
    f = netCDF4.Dataset(self.file,'w')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: runTest (tst_compound_alignment.CompoundAlignTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_compound_alignment.py", line 84, in setUp
    dataset = netCDF4.Dataset(self.file, "w")
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: testing compound attributes
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_compoundatt.py", line 34, in setUp
    f  = Dataset(self.file, 'w')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: testing compound variables
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_compoundvar.py", line 44, in setUp
    f  = Dataset(self.file, 'w')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: testing zlib and shuffle compression filters
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_compression.py", line 48, in setUp
    write_netcdf(self.files[0],False,None,array)
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_compression.py", line 18, in write_netcdf
    file = Dataset(filename,'w')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: testing dimensions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_dims.py", line 31, in setUp
    f  = netCDF4.Dataset(self.file, 'w')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: testing endian conversion capability
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_endian.py", line 91, in setUp
    create_file(FILE_NAME,'NETCDF4_CLASSIC',data); self.file=FILE_NAME
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_endian.py", line 12, in create_file
    dataset = netCDF4.Dataset(file,'w',format=format)
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: testing enum data type
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_enum.py", line 25, in setUp
    f = Dataset(self.file,'w')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: Test with a variable that has two unlimited dimensions.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_fancyslicing.py", line 42, in setUp
    f = Dataset(file_name,'w')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: testing 'fancy indexing'
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_fancyslicing.py", line 42, in setUp
    f = Dataset(file_name,'w')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: test_set (tst_fancyslicing.VariablesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_fancyslicing.py", line 42, in setUp
    f = Dataset(file_name,'w')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: testing groups
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_grps.py", line 44, in setUp
    f  = netCDF4.Dataset(self.file1, 'w')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: testing implicit group and creation and Dataset.__getitem__
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_grps2.py", line 18, in setUp
    f = netCDF4.Dataset(self.file,'w')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: testing auto-conversion of masked arrays and packed integers
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_masked.py", line 40, in setUp
    file = netCDF4.Dataset(self.file,'w')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: testing auto-conversion of masked arrays and packed integers
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_masked2.py", line 34, in setUp
    f = Dataset(FILE_NAME1,'w')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: runTest (tst_masked3.GlobalSetAutoMaskTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_masked3.py", line 142, in setUp
    f = Dataset(self.testfile, 'w')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: Testing auto-conversion of masked arrays for set_auto_mask(False) with scaling
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_masked3.py", line 30, in setUp
    f = Dataset(self.testfile, 'w')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: Testing auto-conversion of masked arrays for set_auto_mask(False)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_masked3.py", line 30, in setUp
    f = Dataset(self.testfile, 'w')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: Testing auto-conversion of masked arrays for set_auto_mask(True)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_masked3.py", line 30, in setUp
    f = Dataset(self.testfile, 'w')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: Testing auto-conversion of masked arrays for set_auto_mask(True)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_masked3.py", line 30, in setUp
    f = Dataset(self.testfile, 'w')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: runTest (tst_multifile.NonuniformTimeTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_multifile.py", line 71, in setUp
    f = Dataset(file,'w',format='NETCDF4_CLASSIC')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: testing multi-file dataset access
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_multifile.py", line 22, in setUp
    f = Dataset(file,'w',format='NETCDF4_CLASSIC')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: runTest (tst_multifile2.NonuniformTimeTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_multifile2.py", line 73, in setUp
    f = Dataset(file,'w',format='NETCDF4_CLASSIC')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: testing multi-file dataset access
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_multifile2.py", line 22, in setUp
    f = Dataset(file,'w',format='NETCDF4_CLASSIC')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: test_failure (tst_netcdftime.TestDate2index)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_netcdftime.py", line 510, in setUp
    f = Dataset(self.file, 'w')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: test_issue444 (tst_netcdftime.TestDate2index)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_netcdftime.py", line 510, in setUp
    f = Dataset(self.file, 'w')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: test_list (tst_netcdftime.TestDate2index)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_netcdftime.py", line 510, in setUp
    f = Dataset(self.file, 'w')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: Check that the fallback mechanism works.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_netcdftime.py", line 510, in setUp
    f = Dataset(self.file, 'w')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: test_select_dummy (tst_netcdftime.TestDate2index)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_netcdftime.py", line 510, in setUp
    f = Dataset(self.file, 'w')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: test_select_nc (tst_netcdftime.TestDate2index)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_netcdftime.py", line 510, in setUp
    f = Dataset(self.file, 'w')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: test_simple (tst_netcdftime.TestDate2index)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_netcdftime.py", line 510, in setUp
    f = Dataset(self.file, 'w')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: test_singletime (tst_netcdftime.TestDate2index)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_netcdftime.py", line 510, in setUp
    f = Dataset(self.file, 'w')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: testing garbage collection (issue 218)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_refcount.py", line 8, in setUp
    nc = netCDF4.Dataset(file_name, mode='w', keepweakref=True, format='NETCDF4')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: testing renaming of dimensions, variables and attribute deletion
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_rename.py", line 27, in setUp
    f  = netCDF4.Dataset(self.file, 'w')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: testing scalar variables
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_scalarvar.py", line 22, in setUp
    rootgrp = netCDF4.Dataset(self.file, 'w')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: runTest (tst_scaled.GlobalSetAutoScaleTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_scaled.py", line 189, in setUp
    f = Dataset(self.testfile, 'w')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: Testing auto-conversion of masked arrays for set_auto_mask(False) with masking
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_scaled.py", line 34, in setUp
    f = Dataset(self.testfile, 'w')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: Testing (not) auto-scaling of variables for set_auto_scale(False)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_scaled.py", line 34, in setUp
    f = Dataset(self.testfile, 'w')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: Testing auto-scaling of variables for set_auto_scale(True) with masking
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_scaled.py", line 34, in setUp
    f = Dataset(self.testfile, 'w')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: Testing auto-scaling of variables for set_auto_scale(True)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_scaled.py", line 34, in setUp
    f = Dataset(self.testfile, 'w')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: Testing automatic packing to all kinds of integer types
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_scaled.py", line 34, in setUp
    f = Dataset(self.testfile, 'w')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: test for issue 90 (array shape should not be modified by
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_shape.py", line 14, in setUp
    f = Dataset(file_name,'w')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: test_0d (tst_slicing.VariablesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_slicing.py", line 18, in setUp
    f = Dataset(file_name,'w')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: test_1d (tst_slicing.VariablesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_slicing.py", line 18, in setUp
    f = Dataset(file_name,'w')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: testing variable slicing
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_slicing.py", line 18, in setUp
    f = Dataset(file_name,'w')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: test_issue259 (tst_slicing.VariablesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_slicing.py", line 18, in setUp
    f = Dataset(file_name,'w')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: test_issue300 (tst_slicing.VariablesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_slicing.py", line 18, in setUp
    f = Dataset(file_name,'w')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: test_issue306 (tst_slicing.VariablesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_slicing.py", line 18, in setUp
    f = Dataset(file_name,'w')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: test_issue371 (tst_slicing.VariablesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_slicing.py", line 18, in setUp
    f = Dataset(file_name,'w')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: test_retain_single_dims (tst_slicing.VariablesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_slicing.py", line 18, in setUp
    f = Dataset(file_name,'w')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: testing functions for converting arrays of chars to fixed-len strings
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_stringarr.py", line 23, in setUp
    nc = Dataset(FILE_NAME,'w',format=FILE_FORMAT)
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: testing primitive data type
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_types.py", line 27, in setUp
    file = netCDF4.Dataset(self.file,'w')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: testing unicode
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_unicode.py", line 18, in setUp
    f = netCDF4.Dataset(self.file,'w')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: testing unlimited dimensions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_unlimdim.py", line 24, in setUp
    f  = netCDF4.Dataset(self.file, 'w')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: testing primitive variables
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_vars.py", line 30, in setUp
    f  = netCDF4.Dataset(self.file, 'w')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: runTest (tst_vlen.TestInvalidDataType)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_vlen.py", line 82, in runTest
    f = Dataset(FILE_NAME, 'w', format='NETCDF3_CLASSIC')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: testing vlen variables
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_vlen.py", line 112, in setUp
    f = Dataset(self.file,'w')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: runTest (tst_vlen.TestScalarVlenString)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_vlen.py", line 98, in runTest
    f = Dataset(FILE_NAME, 'w', format='NETCDF4')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

======================================================================
ERROR: testing vlen variables
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Unidata/netcdf4-python/test/tst_vlen.py", line 35, in setUp
    f = Dataset(self.file,'w')
  File "netCDF4/_netCDF4.pyx", line 1757, in netCDF4._netCDF4.Dataset.__init__ (netCDF4/_netCDF4.c:11409)
  File "netCDF4/_netCDF4.pyx", line 1159, in netCDF4._netCDF4._set_default_format (netCDF4/_netCDF4.c:5269)
ValueError: unrecognized format requested

----------------------------------------------------------------------
Ran 76 tests in 33.961s

FAILED (errors=59)
travis_time:end:13a230db:start=1450907170386052091,finish=1450907205034677656,duration=34648625565[0K
[31;1mThe command "python run_all.py" exited with 1.[0m

Done. Your build exited with 1.
